- code/modules/clothing/clothing.dm
- code/modules/clothing/ears/_ears.dm
- code/modules/clothing/glasses/_glasses.dm
- code/modules/clothing/gloves/color.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/research/xenobiology/crossbreeding/_clothing.dm
https://github.com/tgstation/tgstation/pull/56233
A common pattern is clothing that gives a certain trait when equipped in
the correct slot, for example, mesons making you immune to supermatter
madness, or the bartender's beer goggles giving them the ability to
"booze slide".
Now, instead of implementing essentially the same logic on equip and
dropped, it is now supported at the clothing level with the
`clothing_traits` lazylist.
> [Cherry pick] Refactors a common pattern, clothing traits (#56233)

- code/modules/projectiles/projectile/reusable/foam_dart.dm
https://github.com/tgstation/tgstation/pull/56250
fixes a pretty bad exploit with foam darts
- Modify a dart with a pen, giving it 5 damage
- Target someone's mouth (or a monkeyman)
- Fire
- Firing sequence for handle_suicide multiplies damage by 5 on the projectile instance
- Dropped projectile has 25
- Repeat 1 more time for 125 instacrit dart, or another time after that for 600 instakill dart
all discovery credits go to @necromanceranne, this was brought to my attention
> [Cherry pick] [s] fixes damage multiplicative exploit with foam darts (#56250)

- code/modules/awaymissions/mission_code/Academy.dm
https://github.com/tgstation/tgstation/pull/56174
There's a short 1 second delay between rolling the Die of Fate and it actually taking effect, meaning you can spam it in your hand multiple times in order to queue up multiple effects that the user may not actually survive to see if one of the first rolls kills or dusts them. This puts a 2.5 seconds cooldown on being able to roll the Die of Fate to prevent stacking
> [Cherry pick] Puts a short cooldown on the Die of Fate (#56174)

- code/game/objects/items/storage/boxes.dm
Removes Urainum from the debugtools box, as it causes mass death around it, and for ICSpawning of Bluespace Tech
:cl: Miss Fox
del: Urainum from debugtools box
/:cl:
[Remove Urainum from BSTech Debug kit](https://app.gitkraken.com/glo/view/card/75e203abba5549438d94478c812e6f12)
> Removed Rads. Rejoice

- code/modules/modular_computers/hardware/battery_module.dm
Changed the try-eject proc to call qdel if eject was called by something other than a user. (Not that a user can remove the battery anyway, as there is a proc missing for that)
:cl: MissFox
fix: Added missing QDEL for modular computer battery, so its removed on QDEL
/:cl:
[Fix battery on Tablet](https://app.gitkraken.com/glo/view/card/eac3f1a9d7014b85a8e4e9c6f6429ec1)
> 7 Fix battery on Tablet

- code/game/sound.dm
Quick and dirty edit so people don't feel forced to shut off the lobby screen music because of no volume adjustment.  
Proper rewrite of the system will be done at a later point
tweak: Title screen music is now at 60% volume - healthy ears are happy ears
/:cl:
> Lower title music volume from 85% to 60%

- code/modules/atmospherics/machinery/airalarm.dm
- tgui/packages/tgui/interfaces/AirAlarm.js
Adds a really simple heating controller to the air alarm, that heats off a set point defined in the air alarms vars.
:cl: MissFox
add: Added built-in heater to air alarms
/:cl:
[Add Heaters to Air alarms](https://app.gitkraken.com/glo/card/7d520976f1134758aed2e23620324aaf)
> [TM ONLY] 24 Add Heaters to Air alarms

- code/modules/mob/living/carbon/human/species.dm
Fixes the issue with the mutant bodyparts not updating if someone is husked (the system thinks the appearance will be the same, so it doesnt rebuild it, which is a bug)
> Being a husk is now considered for the mutant bodyparts render key

- code/modules/surgery/bodyparts/_bodyparts.dm
If you don't draw grayscale, then you're not using the overriden species icons
There's like 3 ways to go about fixing this, either giving all species their all husked variants (which will probably be good later, especially for differently sized bodyparts)
Or you can set the rendered_bp_icon to null when the bodyparts get a husk
> Fixes husked bodyparts

- code/game/area/areas.dm
Lowered "ship ambience" volume to 10 from 35
Increased ambience volume to 30 from 25
Ambience now is played repeatedly in intervals of 45-60s, rather than 35% on entering an area with 60s cooldown
Sounds better
> Makes ambience better

- code/modules/library/soapstone.dm
---
Soapstone messages no longer persist if their total voting score is -5 or below (might change based on feedback). The game won't save them and old messages beneath the threshold will be set to non-persistent when they load, which means there's one round to save them (you could also just engrave them again).
These have shit up the place for years now regardless of what the consensus on each one is. One of the reasons nobody looks at them is because there's so many, and they're usually of low quality.
At the moment only the soapstone or admins can delete them. I don't think that's been enough to keep them at a manageable amount and decent quality.
I like this feature a lot. I've just thought for years it needed this to make it worthwhile.
🆑 cacogen
tweak: Soapstone messages at or below …
> [Manual Mirror] Soapstone messages voted beneath a certain score don't persist

- code/datums/elements/skittish.dm
- code/datums/traits/good.dm
- code/game/objects/structures/crates_lockers/closets.dm
- code/game/objects/structures/crates_lockers/crates/large.dm
- code/modules/mining/abandoned_crates.dm
- code/modules/mob/living/init_signals.dm
- tgstation.dme
Original PR: tgstation/tgstation#56048
---
🆑 coiax
tweak: The Skittish quirk will now cause you to automatically dive into
a locker/crate if you bump into it (although closets must be closed).
Walk to avoid this behaviour.
/🆑
This makes the quirk more useful, while also making it more thematic,
since the "diving into" behaviour can't be disabled, only supressed by
walking.
The cost is unchanged, as the quirk in its current form is overcosted at
2 points.
The emergent effect of skittish people diving into closets when caught
into explosions is definitely a feature, and not a bug.
---
~~There is some performance work that can be done, (moving the bumping behaviour
from the closet to the mob), but only if this is popular.~~
The "skittish" code is now an element that is added/removed from …
> [Manual Mirror] Reworks skittish quirk to be automatic

- code/datums/brain_damage/creepy_trauma.dm
Mirrored from: tgstation/tgstation#56357
---
---
Adds a special pool to the obsessed target picker, making it so if the obsessed has the Spiritual, Clown Fan, or Mime Fan quirks that they will pick from a smaller pool of Chaplains and Clowns/Mimes if they have the respective quirks.
Thanks to `@Timberpoes` for help with putting this together.
It makes sense that if you're a fan of these jobs that you would likely have them as your obsession target, it also adds to the texture of these jobs. They are all RP-centric, so you're more likely to get some good interactions with them rather than trying to spend your whole shift clawing at the viro airlock so you can get a picture with the reclusive disease person. Adds more texture to the quirks involved.
🆑
tweak: If you're a Clown/Mime fan and …
> [Manual Mirror] Adds Quirk-Related "Special Pool" to obsessed for Chaplain, Clown, and Mime targets.

- _maps/map_files/IceBoxStation/IceBoxStation.dmm
- _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
Mirrored from: tgstation/tgstation#56308
---
---
Icebox's electrical grid has fallen into a sorry state. It never received a full overhaul like Box itself did, and multiple large department updates have happened since the two maps split. This has left the electrical grid not very well connected in places, duplicate APCs existing, and a mix of in maint APCs and in-area APCs. Some of the newer areas used the auto-APC mapping aids, but others used varedited or preset APCs. This moves all APCs into the areas they power and updates them to the new mapping aid. The electrical grid has been updated to accommodate these new APCs and be a bit better connected.
Icebox has also had an issue with very high roundstart active turf numbers recently. At least three separate issues were causing this: the …
> [Manual Mirror] Icebox Electrical Repairs and roundstart active turf fixes

- _maps/shuttles/emergency_medisim.dmm
Mirrored from: tgstation/tgstation#56334
---
---
See title
Consistency! And gives security the ability to properly deny traitors greentext on a shuttle with a brig.
🆑
fix: The Medieval Shuttle's brig now has a brig area instead of its usual area for escape checking
/🆑
> [Manual Mirror] Adds brig area to the medieval shuttle brig

- hrzn/modules/icspawning/code/game/objects/items/cards_ids.dm
- hrzn/modules/icspawning/code/modules/clothing/outfits/standard.dm
qol: Inhand Bluespace Tech IDs are now gold
fix: Fixed Bluespace Tech IDs
/:cl:
> Update path and inhand icons for BST id

- tgui/packages/tgui-panel/chat/renderer.js
Removes the global flag from the chat highlight regex, which caused only every odd entry to work.
fix: Chat highlighting now works for every word, not only every odd one.
/:cl:
> Fix chat highlighting

- _maps/map_files/tradership/tradership3.dmm
- _maps/map_files/tradership/tradership4.dmm
- code/game/shuttle_engines.dm
- code/modules/overmap/propulsion_engine.dm
- code/modules/overmap/shuttle_extension.dm
- tgstation.dme
Adds Propulsion Engines, they operate off of gas, ejecting them to gain speed. The more pressurized(hot) the gasses the more efficient the engines.
I ran into 2 minor atmos bugs that affect the engines (only during manual construction or moving them) that I will be fixing upstream
Actual real engines not based off magic
:cl:
add: Adds Propulsion Engines which are shuttle engines that operate off of gas from connected pipes
add: The FTV Bearcat has had their Burst engines replaced with Propulsion ones, Atmospherics has been accomodated with the pipelines and some cans for them
/:cl:
> Adds Propulsion Engines - adds them to Bearcat too

- code/game/sound.dm
..from 60%.
BYOND is loud enough that you can always raise your volume more if there's a banger.
This will do until there's a better solution, let's keep our hearing for a couple more years AND have people not forced to disable the music.
qol: Lobby music is now at 30% - four ears, rejoice!
/:cl:
> Lower title music volume to 30%

- code/datums/map_config.dm
Fixes a presumably little typo.
This was bothering me enough to do a web edit :notlikethis:
spellcheck: All resesearch stations have been downgraded to research stations. Sorry Reese's Lovers!
/:cl:
> Grammar fix on map info

- code/game/shuttle_engines.dm
- code/modules/overmap/overmap_shuttle.dm
- code/modules/overmap/shield_generator.dm
I tried using late initialize but I was wrooong, and late initialize doesnt initialize after all other subsystems have finished, it seems
:cl:
fix: Fixes shuttle extensions not applying on mapload
fix: Shuttles traversing more than 1 tile per second will now properly move
/:cl:
> Fixes shuttle extensions not applying on mapload and fast shuttle movement fix

- hrzn/modules/emotes/code/dna_screams.dm
- hrzn/modules/emotes/code/emotes.dm
Re-enables some of the disabled emotes for species with checks like Vox' and others, which required #11 
Also does some QoL fixes.
Maybe more to come, hence draft for now.
[#89 - Reenable some emotes, code fixes](https://app.gitkraken.com/glo/card/075831dc29774732807fb30230bbd855)
> Re-enable specific species emotes and some emotecode TLC

- code/modules/mob/living/simple_animal/friendly/mouse.dm
Disables the code for mice to eat wires. As is is a undesirable feature for lowpop servers. quickly destroys the powernet before a crew can even get power started.
:cl:
qol: Disabled mice munching wires
/:cl:
> Disables mice munching wires

- code/__DEFINES/overmap.dm
- code/controllers/subsystem/mapping.dm
- code/datums/map_config.dm
- code/modules/map_content/tradership/tradership_define.dm
Dependant on https://github.com/hrzntal/horizon/pull/244
One random planet now spawns in the overmap
FTV Bearcat spawns 2 planets but no lavaland
:cl:
add: One random planet now spawns on the overmap
add: FTV Bearcat now spawns 2 planets on the overmap, but no lavaland
/:cl:
> One random planet now spawns

- code/modules/overmap/propulsion_engine.dm
- code/modules/overmap/shuttle_extension.dm
People mentioned that the propulsion ones eat too much fuel, and I've noticed that the small shuttles are kinda slow
I've yet to add mass definitions to most shuttles too, as currently only Bearcat and Crow have them set
:cl:
balance: Propulsion engines now take 0.25 fuel instead of 0.7
balance: Engines now grant 0.5 speed instead of 0.35
/:cl:
> Engines are now faster, propulsion engines take less fuel

- code/controllers/subsystem/mapping.dm
- code/datums/map_config.dm
- code/modules/map_content/deltastation_define.dm
- code/modules/map_content/icebox_define.dm
- code/modules/map_content/kilostation_define.dm
- code/modules/map_content/metastation_define.dm
- code/modules/map_content/tradership/tradership_define.dm
- code/modules/map_content/tramstation_define.dm
- code/modules/overmap/overmap_objects.dm
This change was suggested to have more exploration content for now
Icebox spawns 2, due to the small amount of shuttles (I think now 0?) it has. But we probably should give it some
Also removed an unused variable about spawning empty levels, we dont use those
:cl:
add: Space Ruin Levels now spawn properly, most maps spawn 3 of them now
/:cl:
> Space Ruin Levels now spawn properly, most maps spawn 3 of them now

- code/controllers/subsystem/mapping.dm
- code/controllers/subsystem/trading.dm
- code/datums/map_config.dm
- code/modules/map_content/tradership/tradership_define.dm
- code/modules/trading/_trade_hub.dm
- code/modules/trading/trade_hub_overmap.dm
Trading houses now spawn per map_config basis, they will spawn a global network and 2 localized hubs by default.
The hubs can have guaranteed traders and the FTV Bearcat has a guaranteed medical and mining trader in the global network.
Shuttles can now properly access localized trading houses
:cl:
add: Trading houses now spawn per map_config basis, they will spawn a global network and 2 localized hubs by default.
add: The hubs can have guaranteed traders and the FTV Bearcat has a guaranteed medical and mining trader in the global network.
fix: Shuttles can now properly access localized trading houses
/:cl:
> Trading update and fixes

- code/game/machinery/computer/chef_orders/order_datum.dm
- code/modules/research/designs/biogenerator_designs.dm
Adds Meat Product to Chef Order Console and Biogen.
Does what it says on the tin.
It's nice being able to order your own ingredients if you have the money for it. It being available in the biogen removes the need to kill monkeys (but is more expensive than monkey cubes.)
:cl:
add: Adds Meat Product to Chef Order Console and Biogen.
/:cl:
> Adds Meat Product to Chef Order Console and Biogen.

- .github/workflows/pr_autolabel.yml
Adds `edited` to the labeller workflow so labels update when people change their changelog too.
> Aaaaaaa labeeels

- _maps/map_files/tradership/tradership1.dmm
- _maps/map_files/tradership/tradership2.dmm
- _maps/map_files/tradership/tradership3.dmm
- _maps/map_files/tradership/tradership4.dmm
This is the second QoL update for bearcat.
Adding the following:
- All doors and windows now have firelocks
- External airlocks have helpers to stop the mice breaching the ship
- A brig has been added to deck 1 (One cell and some deco)
- There is now a way to end rounds. Departures has been added. the south airlock on Deck 1 now will be able to have the departures shuttle dock to it.
- Minor Deco fixes. added some windows.
- All exterior walls are now R_Walls to improve bearcat's hull from damp paper to dry paper.
:cl:
add: Bearcat - Firelocks to all doors
add: Bearcat - Brig on deck 1
add: Bearcat - Departures shuttle dock on deck 1 south airlock (You can now round end ingame bearcat)
fix: Bearcat - Tile leaking causing atmos to runtime sometimes or take a long time to load.
refactor: …
> Bearcat QoL 2 - Firelocks, Alarms, Departures, Brig

- _maps/map_files/tradership/tradership1.dmm
- _maps/map_files/tradership/tradership2.dmm
- _maps/map_files/tradership/tradership3.dmm
- _maps/map_files/tradership/tradership4.dmm
Part 3 of the Bearcat QoL updates;
**Disposals**
- Added a new room to ship: Disposals. North east on deck 1.
Note: SEE LAST UPDATE, THIS HAS BEEN CHANGED
- Piped decks 1-3 with disposals system. All rooms that create trash have a disposals bin. other places just have normal bins.
- Xenobio now has a disposals straight to space. for getting rid of those pesky monkeys
**Lights**
- Added lightswitches to all rooms and main walkways. ready for upcoming PR to port roundstart lighting fun.
- Added some marker beacons to external airlocks and disposal outlets.
**Misc Fixes**
- Fixed another missing wire.
- Added the missing airalarm in chems.
:cl:
qol: Bearcat QoL Part 3: Disposals and Lights -- See PR for more details
/:cl:
> Bearcat QoL Part 3: Disposals and Lights

- code/modules/overmap/planets/planet_types/barren_planet.dm
oops
:cl:
fix: Barren planets mistakenly no longer have sandstorms
/:cl:
> Barren planets mistakenly no longer have sandstorms

- code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
Does what it says on the tin
Doesn't serve much purpose for us.
Also spams the admin log with unnecessary messages.
del: Stationary nuke disk no longer raises loneops weight
qol: Nuke disk likes to be tucked into bed even more now.
/:cl:
> Removes loneops weight increase from stationary nuke disk

- code/datums/emotes.dm
You'll still receive the emote if you have them in your sight
No useless chatspam and more performance cause viewers() wont be run every each AI emote
:cl:
fix: Client-less mobs no longer send their emotes to ghosts through global ghost sight
/:cl:
> Client-less mobs no longer send their emotes to ghosts through global ghost sight

- code/game/shuttle_engines.dm
- code/modules/overmap/mining_laser.dm
- code/modules/overmap/propulsion_engine.dm
- code/modules/overmap/shield_generator.dm
- code/modules/overmap/shuttle_extension.dm
- code/modules/overmap/transporter.dm
- code/modules/shuttle/shuttle.dm
This issue would happen anytime a shuttle would take more than 1 server tick to load in, due to the timer
All extensions now use the shuttle's `connect_to_shuttle` proc to make sure there's no initialization issues. As the shuttles load, it gets added to the shuttle list before linkup() (calling `connect_to_shuttle`) and not after, as linkup'd things may require that
EDIT: ~~wait now it turns out that maploaded shuttles stop attaching their extensions :joy:~~
EDIT2: Turns out linkup() would only be called on duplicate shuttles, and only was used to append ID's of buttons and stuff. I've changed it so it's always called and all the things wanting to link to a shuttle can safely use it now. All good and ready now
:cl:
fix: Fixes shuttle extensions often not applying to non-maploaded …
> Fixes shuttle extensions often not applying to non-maploaded shuttles

- code/modules/balloon_alert/balloon_alert.dm
- code/modules/client/preferences.dm
This only applies to the chat text that is not defined and gets copied from balloon popup text. There's a dash inbetween the user and the text
:cl:
add: Wraps chat text of balloon alerts in notice span and adds a source prefix
/:cl:
> Wraps chat text of balloon alerts in notice span and adds a source prefix

- _maps/shuttles/luxury_ironwrought.dmm
- code/datums/shuttles.dm
- code/game/area/areas/shuttles.dm
- code/modules/shuttle/luxury.dm
Adds another ship that is designed for the ship system (and buying now!) that provides an environment for a mineral recovery system. The ship's design is that of an ironworks, and has some small mining gear as well as an ORM. These work great in tandem with the other ships created as they function as very basic but very functional drop-in departments for a planetary excursion. Landing these ships together is a feat, but it can be done - setting up a small colony system quickly.
Great potential for roleplay, and as requested, makes more ship types available. Designed to be a balanced and expensive drop-in department for any rich and growing crew. Ideally used planetarily to provide a great engineering environment and roleplay, complete with sweaty ironworkers!
:cl:
add: Adds The …
> Luxury shuttle ironwrought

- code/__DEFINES/trading.dm
- code/modules/trading/_trader.dm
- code/modules/trading/traders/goods.dm
Traders if have less than 50% their starting cash they'll receive paychecks over time.
Traders now also have 7000 cash from 5000 and the Rock n Drill trader now has 15000
:cl:
add: Traders if have less than 50% their starting cash they'll receive paychecks over time.
add: Traders now also have 7000 cash from 5000 and the Rock n Drill trader now has 15000
/:cl:
> Traders paycheck and credits tweak

- code/game/turfs/change_turf.dm
- code/game/turfs/turf.dm
- code/modules/shuttle/on_move.dm
Kind of rather important fix
:cl:
fix: Turfs now properly restore areas after shuttle movements
/:cl:
> Turfs now properly restore areas after shuttle movements

- code/game/turfs/closed/minerals.dm
:cl:
fix: You will now be able to excavate rock turfs properly
/:cl:
> Fixes mineral rock attackby() not calling parent (excavation fix)

- code/_onclick/hud/parallax.dm
- code/modules/overmap/overmap_shuttle.dm
- code/modules/overmap/overmap_shuttle_process.dm
- code/modules/overmap/shuttle_control_component.dm
- code/modules/shuttle/shuttle.dm
:cl:
add: Overmap shuttles will now properly respect velocity to animate parallax
fix: Fixes parallax oddities.
fix: Client's parallax is now updated immediately when an overmap object changes its movement state
/:cl:
> Fixes parallax oddities and overmap shuttle parallax

- code/modules/food_and_drinks/recipes/food_mixtures.dm
Adjusts food crafting speed from 30 deciseconds, to 5.
For "good" foods, IE, Burgers, Tacos, ect, the time to craft is fine. For "lesser" foods, or foods with multiple steps, it's an absolute pain. This is kind of a bandaid fix for food to be somewhat bearable until things are changed.
:cl:
qol: Food is significantly faster to craft.
/:cl:
> Makes food crafting faster.

- code/modules/mining/machine_vending.dm
Adds a basic variant of the mining conscription kit. By itself, this PR does nothing, but I'm hoping Bee will be able to add it to the mining trader/merchant. I mostly don't want to cause conflicts with the stuff they're working on.
Kit contains:
- Explorer Suit/Mask
- Pickaxe
- Lantern
- Mining Bag
They buy materials, so, it'd make sense that they would be willing to sell some basic mining supplies. Instead of adding like, three individual orders for products, I made it a kit.
:cl:
add: Basic Mining Kit
/:cl:
> Basic Mining Kit

- code/controllers/subsystem/processing/quirks.dm
- code/datums/quirks/negative.dm
Adds
- insulin
- spaceacillin
- saline glucose
- coagulant
to the allergy quirk blacklist.
Renames that quirk to "Medicine Allergy", and adjusts its points
Adds an `/extreme` subtype  that inherits from the above and only leaves `insulin` and `saline glucose` as added blacklist items. Because its pretty much impossible to be allergic to those.
Adds a nice middle ground as an allergy perk, and also an extreme variant back incase someone really wants to die. Yet makes it a bit less awful as well.
qol: Medicine Allergy Quirk now has insulin, spaceacillin, sal-glucose solution and coagulant in their blacklist - no more allergies from those
balance: Medicine Allergy Quirk only gives 4 points now
add: Re-added Extreme Medicine Allergy
balance: Extreme Medicine Allergy now has …
> Makes existing allergy quirk nicer, adds extreme subtype

- code/modules/surgery/bone_mending.dm
20/30 chances respectively. 
As per request of https://github.com/hrzntal/horizon/issues/385
Most surgeries do have inefficient ghetto ways of doing them, with the exception of this which was probably an oversight when introducing wounds
:cl:
add: Wrench can be used in setting/repairing bone surgery as a ghetto tool, it'll be very ineffective though
/:cl:
> Wrench can be used in setting/repairing bone surgery

- code/__DEFINES/preferences.dm
- code/__HELPERS/customization/mobs.dm
- code/__HELPERS/mobs.dm
- code/_globalvars/customization/lists.dm
- code/modules/admin/create_mob.dm
- code/modules/awaymissions/corpse.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/dead/new_player/body_markings/body_marking_sets.dm
- code/modules/mob/dead/new_player/body_markings/body_markings.dm
- code/modules/mob/dead/new_player/preferences_setup.dm
- code/modules/mob/dead/new_player/sprite_accessories.dm
- code/modules/mob/dead/new_player/sprite_accessories/hair.dm
- code/modules/mob/dead/new_player/sprite_accessories/underwear.dm
- code/modules/mob/dead/new_player/sprite_accessories/vox.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/simple_animal/hostile/zombie.dm
Underwear, undershirts and socks now have bodytype restrictions
Hairstyles and facial hairstyles now have bodytype restrictions
Markings and marking sets now have bodytype restrictions
Mutant parts now have bodytype restrictions
All bodytype restrictions can be bypassed with mismatched parts if you wanna make abominations
By the effect of those changes, Voxes will now randomize into their special hair, and their hair will be unable to be picked by people not having mismatched parts (and not be able to be randomized into)
Moved the hairstyle next and previous change arrows before the hairstyle name
Hairstyles now use a smart cache for getting the next/previous one, to ensure the right types are in the pool
Selecting a new species now properly randomizes everything except features
Fixes a …
> Bodytype backend for all appearance stuff, fixes and cleanups

- code/datums/elements/climbable.dm
- code/game/objects/structures/railings.dm
Climbable element now has a climb_over argument.
With that argument it will only allow climbs from within and opposing the atom (based off dir), and will properly move climbers on the other side if they're on the atom they're climbing
:cl:
add: Climbable element now has the functionality of climbing over things
fix: Fixed climbing over railings
/:cl:
> Climbing over things, railing fix

- code/datums/elements/turf_transparency.dm
Port of https://github.com/tgstation/tgstation/pull/60064
Because my transparency block cares about this and I needed to adjust code to include my signal too
:cl:
fix: turf transparency properly not updating when a transparent turf was built over
/:cl:
> Fixes a turf signal unregistration I missed, makes the transparent turf element detach (#60064)

- code/modules/trading/bought_goods/food.dm
- code/modules/trading/sold_goods/food.dm
- code/modules/trading/sold_goods/goods.dm
- code/modules/trading/traders/food.dm
- code/modules/trading/traders/goods.dm
- tgstation.dme
- Organized sold food file.
- Adjust farming apprentice prices.
- Adjust basic mining kit price.
- Adjust atmos trader prices.
- Added space suit to atmos trader.
- Food Traders will buy (some) ingredients or products.
- Fixed a tiny error with atmos vendor. (wrong variable?)
Tested it a few times last night, everything -should- be working.
Adds a way to get space suits. Also allows the chef and botanist to contribute to Bearcat Economy
:cl:
add: Food traders will buy select goods.
add: Atmos traders now carry a space suit.
balance: Adjusted multiple trader prices.
/:cl:
> Trader Adjustments

- _maps/RandomRuins/Planet/abandoned_containment.dmm
- _maps/RandomRuins/Planet/weather_station.dmm
- code/modules/map_content/ruins/planetary/planet_ruins.dm
Adds two new planetary ruins to the game, one medium sized, and one small.
Two new planetary, randomly spawnable ruins are added.
One is an adandoned base, containing several decent loot spawns, an ancient hardsuit, and a dangerous secret.
The second is a dormant weather research outpost, lying silent until the next labcoat settles in for a months-long shift.
Exploration variety is good, and having loot able to be found is helpful and exciting for players looking for salvage-oriented gameplay.
:cl:
add: Added two new planetary ruins, abandoned_containment and weather_station, as well as the code to spawn them.
/:cl:
> Two new planetary ruins.

- code/modules/projectiles/projectile/special/plasma.dm
Mining mechs literally cant fight fauna because their guns tickle them because TG made all plasma blasts deal 1/4th of the damage because adv cutters are printable weapons. I dont like the low damage of cutters and adv cutters, but I do agree that they're printable weapons and high damage for them would be bad. But damage of a mech weapon being lower than a TOOLBOX is a joke
Bulky mech weapons shouldn't have a lower damage than a toolbox (and 1/3 of the DPS because of fire rate)
:cl:
balance: Buffs the mech plasma cutter blasts to 25 dmg from 10 dmg
/:cl:
> Buffs the mech plasma cutter blasts to 25 dmg from 10 dmg

- code/game/objects/items/stacks/sheets/leather.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/game/objects/structures/crates_lockers/crates.dm
Adds a submenu for plasteel crafting to make most unsecured crate types. Adds Gear Harness and Satchels as craftables as well. Also changes crates to give plasteel. It's -technically- possible for crates to be profitable to craft, but its very little money.
I like organizing. Themed crates help me remain organized.
:cl:
balance: Crates drop 2 plasteel instead of 2 iron now.
add: Crates, satchels, and gear harnesses can now be in-hand crafted with plasteel, cloth, and leather.
/:cl:
> Adds crates to in-hand crafting. Satchels and Gear Harnesses too.

- code/modules/research/designs/mechfabricator_designs.dm
- code/modules/research/techweb/all_nodes.dm
- code/modules/surgery/organs/ipc.dm
- code/modules/vehicles/mecha/mech_fabricator.dm
- Added IPC/Synth Organs to Mechfab
- Added Vox Lungs to Mechfab
- Fixed IPC lung icon.
It's nice to be able to fix someone after they've been EMP'd. Or if they've lost their arm implant somehow.
:cl:
add: Mechfab can print IPC/Synth/Vox Parts
fix: IPC lungs are now visible.
/:cl:
> Makes IPC / Vox organs printable.

- code/modules/reagents/withdrawal/generic_addictions.dm
Does what it says on the tin
Tagged as fix because this is just utter deranged shit.
Because 
- It's non-sensical
- its "fun" to *cough every 2 seconds because you didnt smoke for a minute.
fix: Removed coughing from nicotine withdrawal stages.
/:cl:
> Removes coughing from nicotine withdrawal

- code/datums/components/overlay_lighting.dm
- code/game/objects/effects/overlays.dm
This is the proper way to fix it, and it's going to be in standard with how static lighting overlays too, it that means not striking through z levels, which is good
:cl:
fix: Dynamic lighting no longer strikes through z levels, behaves like static lighting now
fix: Fixed dynamic lighting not working for real
/:cl:
> Dynamic lighting fix for real

- code/modules/mob/living/living.dm
Only when you are standing and you do get knocked, so several knockdowns while you're lying down it wont override your intent back if you set it back to stand up
closes https://github.com/hrzntal/horizon/issues/58
Bad for gameplay sometimes, good for character agency and roleplay
:cl:
qol: Getting floored will set your resting status
/:cl:
> Getting floored will set your resting status

- code/game/objects/items/storage/boxes.dm
A lot of things require a crowbar to be at hand, even just for survival.
This remedies those situations.
An even smaller version is to be added later to replace this bandaid, with a special "emergency crowbar"
qol: Your internals box now contains a pocket crowbar for emergencies. Please handle with care.
/:cl:
> Adds a pocket crowbar to the internals box

- code/modules/trading/sold_goods/goods.dm
- code/modules/trading/traders/goods.dm
You buy it and it spawns anchored to the ground and there's nothing you can do with it anyway without a chemistry plumber, which if you have, there's no reason for you to buy the pump because the plumber can spawn those
:cl:
del: Removes the liquid pump from the mining trader
/:cl:
> Removes the liquid pump from the mining trader

- code/__DEFINES/pollution.dm
- code/game/turfs/open/_open.dm
- code/game/turfs/turf.dm
- code/modules/hydroponics/grown/towercap.dm
Added an option to cap the pollution emission, and does so for Bonfires, since they're a powerful pollution emitter that can be running effortlessly for a very long time
:cl:
fix: Added emission caps for pollution
/:cl:
> Emission caps for pollution

- _maps/map_files/tradership/tradership1.dmm
- _maps/map_files/tradership/tradership2.dmm
- _maps/map_files/tradership/tradership3.dmm
- _maps/map_files/tradership/tradership4.dmm
Added:
Fire closets
Oxygen closets
Fire extinguisher cabinets
Engineer closet
Atmos closet
Electrical supplies closet (contain insuls)
Welding supplies closet
Portable scrubbers
Space heaters
Some more water tanks here and there
Fixes the SM blast door being opened by medbay shutter, and now it has its own button
The circuit imprinter is no longer a sci departmental one, but instead an omni one, so people don't have to flip it (or be confused) every shift
:cl:
add: Added a lot of missing equipment to the FTV Bearcat
fix: Fixed SM shutters opening from the medbay privacy button
/:cl:
> FTV Bearcat missing equipment + fixes

- code/modules/shuttle/sold_shuttles.dm
Summary
Corrects spelling error within MS Vulture's Description and Detailed Desc in Sold_Shuttles.DM 
Purpose of change
While playing with four of my friends on the Bearcat Map. We've bought the Vulture Shuttle which states that it has "Living Quarters" but it instead has one. 
Describe the solution
This simply fixes an inconvenience in lines 29 and 30 
Describe alternatives you've considered
Not submitting this pull request cause I'm a scared boi.
Testing
Compiles Correctly and once within Shuttle Console. States the new description including detailed.
Additional context
:cl:
spellcheck: Fixed an inaccuracy in Vulture shuttle description.
/:cl:
> Changed Vulture Descriptions

- code/game/objects/structures/lattice.dm
Inconsistencies with usage of catwalk being used on-tiles and on-openspace often makes the catwalks look a bit weird, which bothers me.
No changes to plated catwalks
:cl:
add: Catwalks can now only smooth with themselves again
/:cl:
> Catwalks can now only smooth with themselves again

- code/datums/emotes.dm
- code/modules/mob/emote.dm
- code/modules/mob/living/carbon/emote.dm
- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/living/emote.dm
- code/modules/mob/living/silicon/ai/emote.dm
- code/modules/mob/living/simple_animal/slime/emote.dm
Running emotes is actually asynchronous because they're invoked by player input which is called by internal byond magic which can happen in the middle of a proc during a byond operation.
A variable set to a singleton may not be what it was intended to be when the proc is supposed to finish running, due to another person invoking the same emote in the same time.
This is what caused that outrageous "ERP swap" bug.
This PR makes it a local argument
Also removed an unused variable from *me emote that I forgot to commit a removal in Subtler PR
:cl:
fix: Fixes asynchronous emote overwrite bug
/:cl:
> Fixes asynchronous emote overwrite bug

- _maps/map_files/tradership/tradership2.dmm
- _maps/map_files/tradership/tradership3.dmm
- _maps/map_files/tradership/tradership4.dmm
- _maps/map_files/tramstation/tramstation.dmm
- code/game/turfs/open/openspace.dm
- code/game/turfs/open/space/space.dm
Ports https://github.com/tgstation/tgstation/pull/63559
Previously the openspace turf for space was a simulated planetary tile, which had a memory, initialization and performance cost.
Not only that but that was a cause of a bug of openspace space tiles actually being mutable, and you could see SM waste flow onto the roof of Bearcat.
Removes `/turf/open/openspace/airless/planetary` so nobody uses it instead of the proper one
:cl:
fix: Creates /turf/open/space/openspace to properly simulate openspace space behaviours and help on performance
/:cl:
> Creates /turf/open/space/openspace

- code/__HELPERS/_lists.dm
- code/datums/ai_laws.dm
- code/datums/looping_sounds/item_sounds.dm
- code/datums/looping_sounds/machinery_sounds.dm
- code/game/machinery/computer/arcade/orion.dm
- code/game/objects/effects/spawners/lootdrop.dm
- code/game/turfs/closed/minerals.dm
- code/modules/meteors/meteors.dm
- code/modules/mob/living/simple_animal/friendly/cat.dm
Ports https://github.com/tgstation/tgstation/pull/62940 and https://github.com/tgstation/tgstation/pull/63035
This fixes an issue that caused our storyteller to pick a weight 0 event of LONE OPERATIVE.
:cl:
fix: Fixed pickweight sometimes picking badly.
/:cl:
> pickweight maintenance and fixes

- code/game/turfs/open/space/space.dm
- code/game/turfs/turf.dm
It's the mining bug with the air pressure thing that recently cropped up because of virtual levels. Turns out `HandleInitialGasString()` needs virtual level information, and it was inherited a tiny bit later
:cl:
fix: Fixes scraped turfs not having planetary atmospherics
/:cl:
> Fixes scraped turfs not having planetary atmospherics

- code/modules/events/aurora_caelus.dm
Before you can ask your coworker to see the Aurora with you, and before you make your way to departures, like, a minute and a half will pass and the event would be ending by now. Now it's a bit longer.
:cl:
add: Makes Aurora Caelus last 3 minutes
/:cl:
> Makes Aurora Caelus last 3 minutes

- code/modules/recycling/disposal/bin.dm
This used to prevent the sounds played from the same tick, because conveyor belts moved everything in a belt to another one at the same time, but now they move things over time to prevent lag, and this cooldown doesnt stop the sound issue anymore.
Changing the cooldown from 1 tick to 2 seconds will prevent the sound issue
:cl:
add: Flushing things via disposals can no longer ear violate you.
/:cl:
> Better cooldown for disposal flush sound

- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/interview/interview.dm
- code/modules/mob/dead/new_player/login.dm
People will no longer need to get 90 seconds of living time in order to bypass interviews because interview status is now saved across rounds in their prefs.
:cl:
fix: Accepted interviewees will no longer need to do 90 seconds of living time in order to save their bypass status.
/:cl:
> Save interview status

- code/modules/mob/living/emote.dm
You can no longer sent empty messages with the second emote input.
The second emote input returns better without an annoying tgui box appearing
:cl:
fix: Better returns for emoting without the first parameter
/:cl:
> Better returns for emoting without the first parameter

- code/__HELPERS/unsorted.dm
- code/controllers/configuration/entries/game_options.dm
- code/datums/ert.dm
- code/datums/helper_datums/getrev.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/ert.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/client/preferences.dm
- code/modules/jobs/job_types/_job.dm
- config/game_options.txt
Removes ENFORCE_HUMAN_AUTHORITY and FORCE_RANDOM_NAMES configs.
FORCE_RANDOM_NAMES , unlike anonymous themes, randomizes your appearance which fucking sucks.
Appearance bans literally dont make sense for roleplay
Ye olde relics, that were also partially already removed.
Something like species restrictions can be configured per map per job basis too.
:cl:
del: Removes ENFORCE_HUMAN_AUTHORITY and FORCE_RANDOM_NAMES configs
del: Removes appearance bans
/:cl:
> Removes ENFORCE_HUMAN_AUTHORITY and FORCE_RANDOM_NAMES and Appearance bans

- code/__HELPERS/unsorted.dm
- code/_globalvars/lists/mobs.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/holder2.dm
- code/modules/admin/verbs/adminsay.dm
- code/modules/admin/verbs/deadmin_asay.dm
- tgstation.dme
Allows deadminned admins to toggle the use of asay through a verb.
Activation/Deactivation notices other admins.
Deadminned admins talking in asay will have a (D) near their ckey.
Not implemented in the best way, because the admin framework is just a mess. This is the best we get.
:cl:
admin: Asay for deadmins through a verb
/:cl:
> Asay for deadmins through a verb

- code/modules/events/wormholes.dm
-Wormholes are now much more likely to spawn in station areas
-Wormholes spawn less of them (150 from 200) due to bigger density in station areas
Wormholes now roll their turf by rolling a 50% and either:
A. picking a random turf (previous behaviour), which averages in about 70% space and 30% station areas
B. picking a random turf in a random station area
Which brings us to an average of 65% wormhole being in a station area, compared to 30%. Which seems like a much more fun number.
Due to this making the wormholes in a larger density in station, it's numbers were lowered to 150 from 200.
:cl:
add: Wormholes spawn less of them but are much more likely to lead into station areas.
/:cl:
> Wormhole event improvements

- code/controllers/master.dm
- code/modules/client/preferences.dm
- code/modules/mob/dead/new_player/new_player.dm
Game options are only available after server initialization
The new player popup will appear after the server has initialized
closes https://github.com/hrzntal/horizon/issues/723
:cl:
fix: Game options are now only available after init
/:cl:
> Game options only available after init

- code/game/turfs/change_turf.dm
- code/game/turfs/open/space/space.dm
- code/game/turfs/turf.dm
Removing a lattice due to construction is handled here -> https://github.com/hrzntal/horizon/blob/main/code/game/turfs/open/space/space.dm#L145
Fixes https://github.com/hrzntal/horizon/issues/757
:cl:
fix: Changing a turf no longer disintegrates lattices and its subtypes (shuttle moving for example)
/:cl:
> Changing a turf no longer disintegrates lattices

- code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
- code/game/objects/structures/crates_lockers/crates.dm
- code/game/objects/structures/crates_lockers/crates/large.dm
- code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
- code/modules/food_and_drinks/kitchen_machinery/griddle.dm
- code/modules/food_and_drinks/kitchen_machinery/grill.dm
- code/modules/hydroponics/hydroponics.dm
- code/modules/plumbing/plumbers/_plumb_machinery.dm
- code/modules/plumbing/plumbers/destroyer.dm
- code/modules/plumbing/plumbers/plumbing_buffer.dm
- code/modules/reagents/chemistry/machinery/chem_heater.dm
- code/modules/religion/religion_structures.dm
Ports https://github.com/tgstation/tgstation/pull/63964
Makes a lot of the table sized or similar looking proper pass flags, allowing people to throw through them or access stuff that would otherwise be blocked by them (most notably hydroponic stuff blocking all sorts of stuff)
:cl: TemporalOroboros
add: A lot of the table sized stuff will allow you to access stuff or throw items over them, that otherwise wouldn't let you, like hydroponic bays or crates.
/:cl:
> Gives a bunch of table sized and/or shaped things LETPASSTHROW #63964

- code/datums/weather/weather.dm
Reverts hrzntal/horizon#690
This removed the telegraph messages that are important to proper functioning of radiation storm event and preparing for other calamities planetside
I don't want them removed until a better thought out solution is introduced
> Revert "Removes telegraph messages from weather"

- code/game/objects/structures/low_wall.dm
Very likely an explosion would kill a low wall but not the window which seems very weird
Now low walls can't be exploded while their top is obstructed
:cl:
fix: Obstructed low walls cant be deleted through explosions
/:cl:
> Obstructed low walls cant be deleted through explosions

- code/modules/reagents/reagent_containers/borghydro.dm
adds a single, critically important reagent to the reagent dispensing shaker that all service cyborgs are armed with
Synths should be able to get drunk with ease and not have to break in to chemistry to enjoy a cool refreshing glass of synthanol. This PR aims to enable cyborgs with the power to get any synth drunk with ease.
:cl:
qol: Adds Synthanol to service cyborgs. Rejoice and get drunk!
/:cl:
> Adds synthanol to service cyborgs.

- code/modules/mob/living/living.dm
Fixes https://github.com/hrzntal/horizon/issues/687
`onZImpact` won't happen on openspace unless some atom blocks your fall, and your fall does not get intercepted, at which it makes no sense to check the turf
:cl:
fix: Fixes crashing into obstructed openspace
/:cl:
> Fixes crashing into obstructed openspace

- code/modules/shuttle/emergency.dm
This will make the pods function like previously, but they'll only work with lavaland
A real integration of pods into lavaland will be much more work.
Fixes https://github.com/hrzntal/horizon/issues/773
:cl:
fix: Emergency Pods now work normally, sort of
/:cl:
> Emergency Pod bandaid fix

- code/modules/cargo/packs.dm
I believe at one point they were removed from the TG base
If you want money to matter, you need to have valuable things being able to be purchased with that money
So here are the hardsuits once again
Some amount of strings and values were taken from Citadel codebase because I couldn't find them with version control here
Introduces:
Security Hardsuit pack
Medical Hardsuit pack
Engineering Hardsuit pack
Atmos Hardsuit pack
Prototype Hardsuit pack
Emergency fragile spacesuits (2)
Space suit crate now gives the EVA space suit, instead of the generic space suit (ugly looking)
More things to spend money on, making money more valuable
Filling the very barren cargo catalogues with worthwhile stuff.
:cl:
add: Re-adds hardsuits and spacesuits to cargo packs
add: Space suit crate now gives the EVA …
> Re-adds hardsuits and spacesuits to cargo packs

- code/modules/mining/equipment/kinetic_crusher.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
fixs #790 
Adds a welded version of the Kinetic Crusher for mining borgs so they can effectively mine without the PK 
:cl:
add: Kinetic Crusher to Mining borgs
/:cl:
> Adds Kinetic Crusher to Mining  borgs

- code/datums/status_effects/neutral.dm
- code/game/objects/structures/icemoon/cave_entrance.dm
- code/modules/mining/abandoned_crates.dm
- code/modules/mining/lavaland/necropolis_chests.dm
- code/modules/mining/machine_vending.dm
- code/modules/mining/minebot.dm
- code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
- code/modules/projectiles/guns/energy/kinetic_accelerator.dm
- code/modules/research/designs/mining_designs.dm
- code/modules/uplink/uplink_items.dm
Renames the upgrades for the Kinetic Accelerator from /obj/item/borg/upgrade/modkit
to
/obj/item/modkit
Removes snowflake borg code that prevents borgs upgrading there Kinetic Accelerator
Removes the upgrades from the MECHFAB (They were the same thing as the vendor spit out. zero diffrances aside from a type setting)
Cleans up more snowflakey borg code from the game.
While also giving a little more freedom to borgs.
:cl:
refactor: Kinetic Accelerator Upgrades
add: Borgs can now upgrade there KA like any other mob
/:cl:
> Refactors Kinetic Accelerator Upgrades

- tgui/packages/tgui/interfaces/NtosNetChat.js
Fixes a bluescreen caused by a nullkey when in admin mode.
NTOS bluescreens in the chat client because it attempts to render a mute button on a client after the admin mode has "removed" them from the room.
Added a null check to prevent this from happening, so it will check the type exists rather than just exploding.
Thanks to TG Station old prs for helping find this issue.
Fixes #798
:cl:
fix: NTOS Bluescreen on chat client when in admin mode
/:cl:
> Fixes NTOS Chat client Bluescreen when in admin mode

- code/modules/power/lighting.dm
• Adds a define for each pixel-shift for easy changing for `NORTH`, `EAST` and `WEST` directionals.
• Sets offsets for north lights to 22, and East and West to 12 and -12 respectively.
Looks better for the lights to be on the top of the walls instead of on the floor at the bottom of the walls.
Obviously, any wall mounts placed by TG prior to TG #58809 where directional mounts were introduced have a chance of being janky if placed on a wall a light is meant to be on.
:cl:
qol: Lights are now by default pixel-shifted onto the walls and windows.
/:cl:
> Offsets directional lights to fit onto our walls

- code/game/turfs/closed/walls.dm
- code/modules/experisci/experiment/types/scanning_material.dm
Fixes https://github.com/hrzntal/horizon/issues/696
Checking truthiness of `target.custom_materials` has been removed as that is the responsibility of `has_material_type`. Turfs don't use the `custom_materials` list as an optimization.
:cl:
fix: fixes experiments that required you to scan a mineral wall.
/:cl:
> Fixes wall scanning experiments

- code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Lowers vision and aggro range of all megafauna
Lowers move speed of Ashdrake, Bubblegum, Colossus, Hierophant
Without those changes you barely have any chance surviving an encounter with any of them due to the changed human move speed, you won't be able to run away and you'll get gibbed eventually.
Accidently breaking a wall to a megafauna shouldn't spell your death.
:cl:
balance: Lavaland megafauna are now slower, and easier to run away from.
/:cl:
> Balances lavaland megafauna

- code/datums/components/overlay_lighting.dm
Updating the light would remove and re-apply the overlay, and then adding the light would apply the overlay, and what would happen is that you wouldn't have any overlay removed, you'd get a new one during the update, and then another extra one during `add_dynamic_lumi`
:cl:
fix: Fixes a rare overlay lighting bug, where it would stack the overlays improperly
/:cl:
> Fixes a rare overlay lighting bug

- code/game/objects/items/devices/PDA/PDA.dm
This would cause the PDA's to get stuck on a non-implemented tab
:cl:
fix: Removes the defunct skill tracker PDA tab
/:cl:
> Removes the defunct skill tracker PDA tab

- code/modules/mining/mine_items.dm
Mining and public mining shuttles no longer use the overmap because the way mining works right now has been designed for a quick travel and ability to recall the shuttle whenever, instead of coordinated expeditions.
:cl:
del: Mining shuttles no longer use the overmap
/:cl:
> Mining shuttles no longer use the overmap

- code/game/objects/structures/shower.dm
- code/game/objects/structures/watercloset.dm
Sinks, showers and urinals now set their offset based on their direction instead of being magicked up from the mapping preset / varedit. All of them also have mapping types for directionals now too
Fixes https://github.com/hrzntal/horizon/issues/915
:cl:
fix: Proper dir offsets and mapping types for bathroom objects
/:cl:
> Proper dir offsets and mapping types for bathroom objects

- code/game/objects/structures/shower.dm
You can now deconstruct showers, and you'll get back their full parts too
Added interaction hints to examine of showers
Closes https://github.com/hrzntal/horizon/issues/916
:cl:
add: Added interaction hints to examine of showers
add: You can now deconstruct showers, and you'll get back their full parts too
/:cl:
> Deconstructing showers

- code/__DEFINES/sound.dm
- code/__HELPERS/roundend.dm
- code/game/sound.dm
*Ever feel.. like your ears explode when you play Space Station 13?
Ever feel.. like the sounds all have the same volume?
Ever feel.. like a plastic bag-* wait.. no.
Anyways-
*Look no further!*
This adds defines and macro for logarithmic audio volumes.
Currently only the lobbymusic has been adjusted to make use of it, but soon more will follow.
Right now this uses an exponent of ², as most other sounds do not use this system, and I'm going to assume that EVERYONE plays with their game on the audio mixer at ~30% or less.
In the future, a target of the mathematical constant e (`NUM_E`) / Euler's number, or `3` would be preferable.
This largely depends on how loud the average of all sound files are, or could even be changed based on what kind of sound category is being controlled.
A good …
> Logarithmic Audio Volume

- code/__HELPERS/unsorted.dm
- code/game/objects/effects/spawners/clear.dm
- code/modules/mapping/map_template.dm
- code/modules/mapping/reader.dm
- code/modules/mapping/ruins.dm
The turf passthrough will no longer clear the turf of its content during spawning ruins.
The map parser now has the functionality of clearing turfs in the loaded maps, instead of that being on the ruin level (needs to be because the parser is the one checking for passthroughs)
You can retain previous behaviours by placing down the `/obj/effect/spawner/clear` map helper wherever you please
Closes https://github.com/hrzntal/horizon/issues/935
:cl:
fix: Ruins will no longer cut every flora and monster in their viscinity when spawned.
/:cl:
> Clearing turfs in the map parser

- code/__HELPERS/customization/mobs.dm
- code/modules/mob/living/carbon/human/species_types/robotic.dm
- config/game_options.txt
Adds synthetic anthromorphs, they currently need to enable mismatched parts to customize properly.
Adds more sanity to randomizing an accessory sprite.
Closes https://github.com/hrzntal/horizon/issues/922
:cl:
add: Synthetic Anthromorphs
fix: More sanity in randomizing sprite accessories
/:cl:
> Synthetic Anthromorphs and more sanity

- code/game/atoms.dm
This was tricky to find.
Basically atoms can modify appearance of already instantiated overlays on `update_overlays` instead of creating a new overlay, and `update_overlays` wouldn't remove the overlays (cause they were modified, so it was a mismatch) before getting new ones.
:cl:
fix: Fixes overlay management conflict
fix: Booze machines will no longer apply indefinite amount of beaker overlays
/:cl:
> Fixes overlay management conflict

- code/__DEFINES/obj_flags.dm
- code/datums/elements/turf_transparency.dm
- code/game/objects/structures/industrial_lift.dm
Currently there's an issue with the tram leaving a hole where it spawns. This can be fixed by updating the turfs transparencies every time the tram is moved, however, this will end up in 35 updates which include networking (vis contents) every time the tram moves on top of already heavy updates it's making. So I'd rather have this flag instead.
:cl:
code: Adds a flag for objects to allow transparency if they block multiz
fix: The tram will no longer leave a black hole where it was first spawned
/:cl:
> Adds a flag for objects to allow transparency if they block multiz

- code/game/objects/items/cards_ids.dm
- code/game/objects/items/devices/PDA/PDA.dm
- code/modules/modular_computers/computers/item/computer.dm
Just a QoL upgrade that got added awhile back on TG. Let's you push credits right onto your PDA or Tablet, and assuming they have an ID inside with a linked account, adds the money.
We get a _**lot**_ of money in the mail. Sucks having to keep pulling out my ID to stick the newly gotten credits in my account. This simplifies things.
:cl:
qol: Put credits straight into your PDA/Tablet
/:cl:
> Deposit Credits in PDA/Tablet

- code/modules/mob/living/carbon/carbon_movement.dm
- code/modules/mob/living/carbon/human/species.dm
Hunger cost is no longer applied twice for being in run intent and moving (You already move faster..)
Bad satiety increases your hunger by 25% instead of 200%.
:cl:
balance: Bad satiety increases your hunger by 25% instead of 200%.
fix: Hunger cost is no longer applied twice for being in run intent and moving
/:cl:
> Some hunger tweaks

- _maps/shuttles/common_petrel.dmm
- _maps/shuttles/common_vulture.dmm
Adds long range holopads to Petrel and Vulture, at Cypress' request.
More forms of long distance communication good.
:cl:
add: adds long range holopads to two shuttles
/:cl:
> Adds Long Range Holopads to Petrel and Vulture

- _maps/shuttles/exploration_crow.dmm
- code/modules/shuttle/sold_shuttles.dm
Touches up the ESS Crow with current assets and some QoL features. 
- Reconfigures the ESS Crow's pipenet to subscribe to the scrubber layer 2/supply layer 4 mapping format, and adds some optimizations.  Hides the propellent gas line and moves the meter closer to the helm. This removes some runtime errors.
- Changes some airlocks to glass, and some to thematic paint schemes.
- Changes the name on the Sold Shuttles from "ESS Crow - sister" to "ESS Crow", and cuts out some of the description text.
- Adds objects that help with the shuttle's immersion.
- Adds a cyborg recharger to the Crow's engineering, allowing for cyborgs to use this shuttle without modification.
- Adds a cargo shutter to the Crow's cargo, allowing for better immersion when loading/unloading cargo and equipment.
- Moves …
> Touches up the ESS Crow

- code/modules/research/designs/machine_designs.dm
- code/modules/research/techweb/all_nodes.dm
Adds LRHPs to techwebs, under the same node requirement as normal holopads (Electromagnetic Theory), and makes them printable from the circuit imprinter.
More availability of long distance communication good, especially for those building on platform shuttles.
:cl:
add: adds long range holopads to the circuit imprinter
/:cl:
> Adds LRHPs to techwebs and circuit imprinters

- code/modules/cargo/goodies.dm
- code/modules/cargo/packs.dm
• Adds the boombox as a cargo goodie pack. It costs 2100cr, slightly higher than going to a vendor (2000cr)
• Adds the RCD crate. Contains one fully-loaded RCD for the price of 2500cr. It costs an absurd 1000cr to buy it at a vendor.
• Changes the changes of pizza crates spawning bombs to 3 in 100 to 3 in 200.
• Removes meme meats from the "excellent meat crate" so it's actually excellent. The crate picks from the list and gives some extras at random. Here's me testing it locally. Fishy, huh?
RCDs are currently the only way to remove ground on icebox. It's a pain to try and actually get the darned thing. The price might be a little cheap, it's up to everyone else to decide.
The meat crate gave you about two useable meats, the rest were xeno, spider legs, human meat and …
> Cargo Pack QoL & Additions (Boombox Goodie, RCD, meat/pizza re-jiggery)

- code/modules/clothing/outfits/ert.dm
• Makes ERT medics both fit for purpose, giving them the tools they need to actually do _stuff_. They now both have defibrillators.
• Regular ERT medic loses their medigun.
• Both ERT medics get a crew pinpointer, advanced medkit (synthflesh), surgery duffelbag, advanced health analyzer and paramedic belt.
• High Alert ERT get night vision medihuds.
ERT medics that spawn currently do not have the appropriate tools to do their job, and have little difference between alert levels.
This PR fully equips both medics, and takes the medigun away from the regular alert ERT. They do have synthflesh to reduce the damage to defib levels, though. Now there's a meaningful difference between the two alerts.
_Okay, this is a bit of a non-issue, but it'd be nice if these outfits weren't scuffed._
:cl: …
> ERT Medic loadout changes

- code/modules/reagents/chemistry/holder.dm
Fixes #1017
This issue happens when you mix two reagents at once and both their mix messages get joined together without a space between. This PR tweaks the join so that each mix message is separated with a space.
Bugs & oversights are bad
:cl:
fix: Making multiple reagents will now actually space the messages properly.
/:cl:
> Fixes mix messages when making multiple reagents

- code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
• Megafauna no longer call the proc to gib and restore health of a target if they are dead, and instead, call the `LoseTarget()` proc that makes simplemobs (incl. megas) disengage.
Please note, the `devour()` proc has not been touched as it is still used by player-controlled megafauna.
Please look at this from the perspective of "why should megafauna gib you?" instead of "why should we remove megafauna gibbing you?".
I think there is more value in giving your fellow miners the prospect of trying to recover your body when it's so close to a megafauna and giving medical a player to revive than there is just removing the player from the round and forcing them to sign up again as a new job.
:cl:
balance: computer-controlled Megafaunas no longer gib their active targets.
/:cl:
> Megafauna will no longer devour (gib) dead targets

- _maps/shuttles/common_pigeon.dmm
- _maps/shuttles/common_rockdove.dmm
- code/game/area/areas/shuttles.dm
- code/modules/shuttle/common_docks.dm
- code/modules/shuttle/sold_shuttles.dm
Adds the CTS (Civilian Transport Shuttle) Pigeon and the EMS (Emergency Medical Shuttle) Rockdove, and allows them to be purchased on the Sold Shuttles console. These are packaged together due to both going into the cheap shuttle niche, with each fulfilling a different role. I've tested both thoroughly to make sure they function and both have minimal runtimes. 
Descriptions and screenshots collapsed into details.
<details>
The Pigeon is a stock-standard shuttle that has no lasers or transporter pad, as its main role is for the transportation of people and supplies. The concept behind this shuttle is to provide overmap travelers with a 'sprinter van'-esq alternative to the larger ESS Crow. This shuttle costs the same as the Petrel, as to fill out the cheap and small shuttle niche. …
> Adds the CTS Pigeon and EMS Rockdove

- _maps/map_files/IceBoxStation/IceBoxStation.dmm
- _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
Fixes all the debug mapping errors I could for now! now with testing!
Missing pipes in engineering, ai sat, medical, and science
a few double cables
a small extension to add an iput to the atmos waste cooling setup
added connectors to the off side of the heat pumps in atmos so they would stop throwing errors in plumbing report
fixed sciences co2 can and coolant loop having no fill port
fixed a stray connector in maints
removed one apc from port maints, starboard primary hallway, and hydroponics
used the power cables going to lower botany to electrify windows
added a blocker around the lower botany windows to block LOS from hostile mobs to reduce the amount of roving vegetarian wolves and bears breaking in.
Mapping bugs are bad!~
:cl:
fix: Plumbing, Power, and Area check debug errors …
> Icebox Fixes (plumb/wire/heatpump errors)

- _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
- _maps/map_files/Mining/Lavaland.dmm
- code/controllers/configuration/config_entry.dm
- code/controllers/configuration/configuration.dm
- code/controllers/subsystem/assets.dm
- code/controllers/subsystem/processing/instruments.dm
- code/datums/datum.dm
- code/game/atoms.dm
- code/game/objects/structures/statues.dm
- code/modules/asset_cache/asset_list.dm
- code/modules/explorer_drone/exploration_events/_exploration_event.dm
- code/modules/explorer_drone/exploration_events/adventure.dm
- code/modules/explorer_drone/exploration_events/danger.dm
- code/modules/explorer_drone/exploration_events/resource.dm
- code/modules/explorer_drone/exploration_events/trader.dm
- code/modules/explorer_drone/exploration_site.dm
- code/modules/instruments/instrument_data/_instrument_data.dm
- code/modules/unit_tests/create_and_destroy.dm
Instead of every single thing requiring an abstract type property it now is on /datum, and don't have to be re-implemented for everything.
Adds a simple proc `is_abstract(path)` which returns whether a datum path is abstract or not.
Converts current implementations to use this unified method.
Future implementations of checking abstractiveness can just use that property and the proc instead of re-implementing it over and over again.
Removes the goliath statues because they were a hack, even using an abstract type.
:cl:
del: It seems someone stole the lifelike Goliath statues.
/:cl:
> Unifies abstract types

- code/modules/mob/living/carbon/human/examine.dm
- code/modules/movespeed/modifiers/mobs.dm
Lowers the slowdown from being overfed, especially important since we already lowered baseline speed.
Changes the description of someone being overfed to appear "stuffed" instead of "quite chubby" as nutrition isn't weight, and I will be implementing proper weight along with height later on.
:cl:
balance: Being overfed slows you down less
spellcheck: Overfed people now appear as "stuffed" instead of "quite chubby"
/:cl:
> Overfed examine and slowdown changes

- code/game/machinery/hologram.dm
Brings over some stuff to cover a couple requests people wanted. When doing holocalls you can now use EMOTES as the caller. Makes sense, since you're standing on the pad so it can visually image your body to the person receiving the call.
Also allows runechat functionality for the hologram.
Just some QoL stuff. That ain't ever gonna hurt nobody!
:cl:
qol: Holograms can now emote. 
qol: Holograms now have runechat support.
/:cl:
> Hologram Emotes and RUNEchat

- code/controllers/subsystem/gamemode.dm
Storytellers didn't update the people counters and population scalling by default which lead to bugs, one most notable was that points were not generated over time unless an admin opened a storyteller panel, which updates its to display correct information on screen.
Also by default the population scalling multipliers are set to 1 instead of 0 so we dont run into those issues again just in case.
:cl:
fix: Fixes Storytellers often not running any events.
/:cl:
> Fixes Storyteller pop scalling bug

- code/modules/modular_computers/file_system/programs/techweb.dm
Changes the access requirement for the techwebs program from RD to Research, as to allow Research staff (scientists/roboticists/geneticists) to download such to modular computers.
Research staff already have access to the RnD console board round start, to allow them to do RnD in the absence of an RD, yet they do not have access to the program itself to download onto modular computers.
In the future, RnD will eventually be replaced with a better system, but it should still receive some balancing tweaks to make it less annoying to interface with.
A concern with doing such is that people might abuse this to hijack RnD's points, by researching random things, but is overall inconsequential with the duration of our rounds. (All of research can usually be completed by the 1hr30m mark, which is …
> Changes Techweb Program Access Requirement

- code/game/machinery/cryopod.dm
Stops an attempt at cryo'ing while someone's buckled to you. Thereby stopping the cryopod from permanently breaking and creating situations like 'cryogenic freezer (Deek-Za) (Deek-Za) (Deek-Za) (Deek-Za)' upon repeated attempts to enter the cryopod. 
Resolves #1129 
People can't accidently (or maliciously) break cryopods.
:cl:
fix: Can no longer attempt to cryo while someone is buckled to you.
/:cl:
> Fix: Can't cryo while buckled

- code/controllers/subsystem/economy.dm
• Switches staffing at the mail sorting office to use avian carriers, specifically owls, as their functionality extends to Sunday.
**Classic example of anti-Avian Carrier misinformation/propaganda. This is a false lie spread by deranged islanders.**
**Evidence of Avian Carrier operating with full functionality on a Sunday.**
Not receiving mail on Sundays feels like a slap in the face to workers who don't have traditional weekends. It's just an arbitrary day of the week where you aren't allowed to have the fun of engaging with the mail feature.
Also, this stops players being forced to rely on bounties for money on Sundays. No mail? No paycheck delivery, no spending money.
:cl:
balance: Avians have been hired at the sorting office to ensure mail is now delivered every day of the week, …
> Changed mail to also be delivered on Sundays

- _maps/shuttles/common_rockdove.dmm
Removes a duplicate APC from the Rockdove
fixing my bad mapping :(
:cl:
fix: removes a duplicate apc from the Rockdove
/:cl:
> Removes Duplicate APC from the Rockdove

- _maps/RandomRuins/IceRuins/icemoon_underground_hermit.dmm
- code/game/area/areas/ruins/icemoon.dm
Gives the hermit ruin its own unique area, instead of it running on the template area.
Reconfigures the amount of lights that are within the ruin.
Moves the sink and changes it to a directional prefab.
<details>
</details>
Having in-use ruins on a template could cause issues further down the line, especially if someone changes the template.
Upkeep also good.
:cl:
add: adds a Hermit Ruin area
qol: moves elements to more sane positions
/:cl:
> Icemoon Hermit Upkeep

- _maps/map_files/KiloStation/KiloStation.dmm
Adds a missing cable from Medbay Surgery
Removes a stray cable from the Freight Dock
Changes the layer of a tank connector to the correct one
Changes a freight dock airlock to be consistent with the one next to it
Changes the telecomms air alarm to the correct server prefab
Fixes good.
:cl:
fix: freight dock fixes and upkeep
fix: missing cable from medbay surgery
fix: changes tcomms air alarm to correct prefab
/:cl:
> Minor Kilo Station fixes

- code/datums/weather/weather_types/radiation_storm.dm
- code/modules/events/radiation_storm.dm
Limits the effects of radstorms to surface-level EVA outside of stations, at Avunia'a request, by restricting the event to only effect outdoors and ground level areas. 
This overall limits the effect of rad storms on station, as the event is in a weird place of being both ineffectual and annoying. It has problems of penetrating multiple z-levels, and needs some overall touchups to how it effects the crew. 
For now, it will be limited as an EVA hazard. 
:cl:
balance: restricts radiation storms to outside of stations
/:cl:
> Limits Radstorms to Outside the Surface of Stations

- _maps/map_files/PubbyStation/PubbyStation.dmm
• Adjusted wallmounts in the service area only, there were things like missing firelocks, missing fire alarms and poor intercom coverage.
• Missing produce console added to kitchen.
• Refridgerators in kitchen coldroom moved into the kitchen itself. It's like having a freezer within a freezer.
• As Pubby is a lowpop map, a few more food items have been placed in the kitchen, mostly as decoration.
• Kitchen now has a mini-stockroom, most of the table-clutter has been moved there to give chefs a clean space to work roundstart without having to find a place to chuck everything.
• Kitchen re-organised heavily to have high-use machinery more front and centre. A notable example is the Condimaster, which is out of the coldroom and in the kitchen itself.
• Condimaster given to the bar.
• Botany …
> Pubby Service QoL/Balance & Fixes

- code/game/machinery/teleporter.dm
Replaces the flyperson mutation from the uncalibrated teleporter with four new outcomes
Namely:
- 100% chance to burn a random limb, badly
- 50% chance to damage an internal organ
- 25% chance to dismember a random limb
- 1% chance to randomize the selected teleport beacon AFTER entry[^1]
**Only one of these will be picked, the percentages are weights**
[^1]: This is more or less not entirely the desired outcome, will be patched soon
Flyperson mutation is nigh impossible to revert currently, and the new options should make more sense and give more interesting results.
:cl:
balance: Teleporters have been updated to not turn crew into flies anymore. However, uncalibrated teleportation is still dangerous and voids your warranty.
/:cl:
> Replace uncalibrated teleporter fly mutation with 4 new outcomes.

- code/game/turfs/closed/wall/misc_walls.dm
• Makes it so mappers can tell regular and rusted walls apart with the same method that is used to make the walls which, are actually greyscale, appear coloured-in for the mapper.
• Closes #1134 which was the reason for doing this.
Makes Cypress happy, fewer chances of making mapping mistakes.
Walls appear as they should in-game.
How this looks in SDMM.
Non-player facing, only helps mappers.
> Makes it easier for mappers to tell if a wall is rusted or not

- code/modules/hydroponics/hydroitemdefines.dm
- code/modules/reagents/chemistry/machinery/chem_dispenser.dm
- code/modules/reagents/reagent_containers.dm
- code/modules/reagents/reagent_containers/spray.dm
Fixes issue #1201 by excluding spray bottles specifically from a couple checks that chem dispensers do since they're the only ones that have restrictive transfer amounts like that.
you can refill spray bottles directly from a dispenser without it taking forever
:cl:
qol: spray bottles can be filled from a dispenser in larger amounts
/:cl:
> exclude spray bottles from transfer amt checks
