hrzntal/horizon

- .github/workflows/ci_suite.yml
- .github/workflows/docker_publish.yml
- .github/workflows/generate_documentation.yml
- .github/workflows/stale.yml
- .github/workflows/update_tgs_dmapi.yml
- update `master` branch actions to `trunk`
- also adjust stale action to 14 - 7, add `Test Merged,Upstream Mirror` labels to exempt
> Update workflow master branches to trunk [ci skip]

- horizon/modules/icspawning/code/_onclick/observer.dm
- horizon/modules/icspawning/code/game/objects/items/cards_ids.dm
- horizon/modules/icspawning/code/modules/clothing/outfits/standard.dm
- horizon/modules/icspawning/code/modules/spells/spell.dm
- horizon/modules/icspawning/code/readme.md
- tgstation.dme
Adds IC Spawning, thanks to Skyrat for code.
:cl: MissFox
add: IC Spawning
/:cl:
> Added IC Spawning

- code/__DEFINES/mobs.dm
> Minimum age is 18

- code/modules/client/verbs/reset_held_keys.dm
> ESC now clears your chat bar input

- interface/skin.dmf
- tgui/packages/tgui-panel/index.js
> Moves chatbar to the bottom of output window

- code/modules/mob/living/carbon/carbon.dm
> Throwing now has a sound and an animation

- code/modules/power/lighting.dm
Title
TG base lighting is very bright, this helps making things a bit more moodey
> Dims light fixtures to 80%

- code/modules/mob/living/carbon/human/human.dm
For something you keep hearing 24/7 its quite loud
> Lowers human footstep noise

- code/controllers/subsystem/events.dm
> Lowers event frequencies to 5 to 15 minutes

- code/modules/events/_event.dm
> Admins now have 60 seconds to cancel an event

- code/game/sound.dm
It's a bit much, this helps it makes it not be too over the top
> Lowers reverb echo

- tools/bootstrap/node_.ps1
- tools/build/cbt/fs.js
- tools/build/cbt/task.js
Probably do not squash this PR?
> Build tools cherry picks

- code/datums/components/singularity.dm
https://github.com/tgstation/tgstation/pull/56242
Fixes #56222
> [Cherry pick] Fix singularities destroying themselves when getting hit with projectiles (#56242)

- code/modules/mob/living/carbon/life.dm
- code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Makes getting drunk much more real and sensible, instead of being like a 5 minute thing after 1 glass
> Makes it harder to get drunk, but drunkiness lasts much longer

- code/__DEFINES/customization/DNA.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/human/species_types/akula.dm
- code/modules/mob/living/carbon/human/species_types/aquatic.dm
- code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
- code/modules/mob/living/carbon/human/species_types/mammal.dm
- code/modules/mob/living/carbon/human/species_types/skrell.dm
- code/modules/mob/living/carbon/human/species_types/tajaran.dm
- code/modules/mob/living/carbon/human/species_types/unathi.dm
- code/modules/mob/living/carbon/human/species_types/vox.dm
- code/modules/mob/living/carbon/human/species_types/vulpkanin.dm
fixes https://github.com/hrzntal/horizon/issues/45
> Fixes broken colors on species

- code/modules/mob/living/living.dm
> Adds Tail Entwining

- _maps/map_files/IceBoxStation/IceBoxStation.dmm
- _maps/map_files/KiloStation/KiloStation.dmm
Added Cryo Pods to Kilo and IceBox Maps.
:cl:
add: Added Cryo to Kilo and IceBox
/:cl:
[Add Cryo to maps in rotation](https://app.gitkraken.com/glo/view/card/61623d355d8f410a95a15f793ec3ef85)
> 31 Add Cryo to maps in rotation

- code/__HELPERS/_logging.dm
- code/modules/admin/verbs/adminpm.dm
Hehe PP
Closes #37
:cl: Foxtrot (Funce)
admin: Player Ckey's in admin logs now open Player Panel rather than starting an ahelp.
/:cl:
[Change admin log CKEY Link to open PP rather than AHELP](https://app.gitkraken.com/glo/card/7a02a8b186744f758798c2460f4feb39)
> PM is now... PP, except when you need to ahelp

- code/__DEFINES/construction.dm
- code/__HELPERS/unsorted.dm
- code/game/atoms_movable.dm
- code/game/machinery/_machinery.dm
- code/game/machinery/cell_charger.dm
- code/game/machinery/doors/windowdoor.dm
- code/game/objects/items/stacks/stack.dm
- code/game/objects/objs.dm
- code/game/objects/structures/grille.dm
- code/game/objects/structures/railings.dm
- code/game/objects/structures/windoor_assembly.dm
- code/game/objects/structures/window.dm
- code/game/turfs/turf.dm
- code/modules/mob/living/living.dm
- code/modules/reagents/chemistry/machinery/reagentgrinder.dm
- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/rcd.dm
Original PR: tgstation/tgstation#56287
---
> [TG Patch] Frame stacking fix and unit test addition. 

- tgui/.yarnrc.yml
Original PR: tgstation/tgstation#56338
---
> [TG Patch] Disabled postinstall scripts until they're fixed in yarn 

- code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
Original PR: tgstation/tgstation#56304
---
> [TG Patch] Splits Grasp of Rust using intents

- code/__DEFINES/hud.dm
- code/_onclick/hud/human.dm
Original PR: tgstation/tgstation#56321
---
> [TG Patch] 1:1 HUD layout fix

- code/__HELPERS/icons.dm
Original PR: tgstation/tgstation#56320
---
> [TG Patch] Removes the persistent hold on a tmp savefile.

- .github/workflows/update_tgs_dmapi.yml
> Make the TGSDM API update workflow use the GH token

- code/modules/surgery/organs/vox.dm
> Webedit EMP brain damage fix

- README.md
* Added website URL
* Updated Discord invite link to our custom solution
* Re-enabled and moved badges to shields.io
> Update URLs and badges on readme

- README.md
> Add a feature label badge, update colours [ci skip]

- code/modules/client/preferences.dm
> Fixes null cultures

- code/datums/keybinding/mob.dm
- code/modules/mob/mob_movement.dm
- code/modules/mob/mob_pixelshift.dm
- tgstation.dme
mob movement go ᵇʳʳʳʳ
add: Port pixelshifting
tweak: You can pixelshift diagonally now!
/:cl:
[Port pixel-shifting](https://app.gitkraken.com/glo/card/58304dc954194a148fbe7aaf138cc101)
> Add pixelshifting

- _maps/map_files/tradership/tradership1.dmm
- _maps/map_files/tradership/tradership2.dmm
- _maps/map_files/tradership/tradership3.dmm
- _maps/map_files/tradership/tradership4.dmm
Map by Azarak
Deco and misc by Missfox
This PR is for easy working on the map while its finished off so we can TM fixes untill finished
:cl:
add: FTV Bearcat map
/:cl:
> FTV Bearcat mapping updates

- code/_onclick/hud/parallax.dm
Fixed a runtime when mobs in nullspace wanted to get a parallax update
:cl:
fix: fixed a runtime with the parallax
/:cl:
> Fixes parallax runtime

- code/modules/overmap/overmap_console.dm
- code/modules/overmap/overmap_shuttle.dm
- code/modules/overmap/shuttle_control_component.dm
- code/modules/shuttle/computer.dm
:cl:
fix: Fixes ghosts being able to use shuttles and overmap
/:cl:
> Fixes ghosts being able to use shuttles and overmap

- code/_onclick/hud/parallax.dm
:cl:
fix: fixed yet another parallax runtime
/:cl:
> Fixes parallax runtime when SSmapping didnt initialzie yet

- .github/workflows/conflicts.yml
- .github/workflows/stale.yml
- README.md
- Updates readme shields/badges to track new labels, grammar
- Updates action labels to our new format
- Updates stale action to v3 - hopefully fixes the spacechar bug
- Updates merge conflict labeller by one commit
> Updates readme, actions, labels in actions [ci skip]

- code/modules/shuttle/arrivals.dm
This allows badminnery with the arrivals shuttle without breaking it
:cl:
fix: Arrivals shuttle human check now checks whether it has the proper destination
/:cl:
> Arrivals shuttle human check now checks whether it has the proper destination

- code/modules/map_content/tramstation_define.dm
:cl:
fix: Fixes tramstation map config for cargo shuttle
/:cl:
> Fixes tramstation map config for cargo shuttle

- .vscode/settings.json
Speedmerge because this is pissing me the fuck off as it constantly dirties my workdir.
Also fixes previewing dmi files in vscode.
> Updates vscode settings to use new association format

- .github/pr_labels.yml
- .github/workflows/conflicts.yml
- .github/workflows/pr_autolabel.yml
- .github/workflows/stale.yml
Replaces the old php-powered hook labeller with a github action.
Should be more solid if this works.
Also updates some workflows again to use the (again) edited labels.
> Automated pull request labels. Now via workflow.

- html/changelogs/AutoChangeLog-pr-253.yml
- html/changelogs/AutoChangeLog-pr-255.yml
> Remove changelogs that shouldn't have been generated 😿

- code/game/objects/items/cigs_lighters.dm
It's kinda stupid how deadly they are
:cl:
balance: Cigarettes now deal 70% less damage to your lungs
/:cl:
> Cigarettes now deal 70% less damage to your lungs

- code/game/objects/effects/spawners/clear.dm
- code/game/objects/effects/spawners/lootdrop.dm
- tgstation.dme
I shall be using those very soon. Also it's a good help for all the mapping stuff out here. Especially the valuables/guns, since them being random in the away_loot spawner makes it much harder to meta
:cl:
add: Adds a variety of loot spawner helpers and a clear terrain helper for mapping
/:cl:
> Adds a variety of loot spawner helpers and a clear terrain helper for mapping

- code/modules/trading/sold_goods/weaponry.dm
I did an oopsie
:cl:
fix: Fixes bad makarov path in trading. Previously it could show up as an AEG
/:cl:
> Fixes bad makarov path in trading

- _maps/map_files/tradership/tradership1.dmm
- _maps/map_files/tradership/tradership2.dmm
- _maps/map_files/tradership/tradership3.dmm
- _maps/map_files/tradership/tradership4.dmm
Big bunch of fixes and changes to bearcat
:cl:
fix: Bearcat - SM Cooling loop (changed to using a thermomech)
add: Bearcat - added RPD to Enginnering
fix: Bearcat - Redesigned the kitchen to add more space
add: Bearcat - Added chembag to chem
add: Bearcat -  Added some clothing and misc vendors to departments and abandoned office
fix: Bearcat -  Added buttons to the lift
fix: Bearcat - Added airlock helpers to all external airlocks
/:cl:
> Bearcat Fixes

- .github/pr_labels.yml
Hopefully does what it says on the tin.
Problem was that the PR body has escaped newlines, which the labeller handled as proper linefeeds. Add some forward slashes and it should pass!
> Fixes, or should fix, changelog-based labels

- code/modules/overmap/planets/planet_types/barren_planet.dm
- code/modules/overmap/planets/planetary_objects.dm
WHY WOULD YOU USE AN EXTRA ABUNDANT DEFINE AND LET PEOPLE MAKE MISTAKES LIKE THIS AAAAA
:cl:
fix: Fixes claw footstep for planetary turfs
/:cl:
> Fixes claw footstep for planetary turfs

- code/modules/lighting/lighting_turf.dm
This is nessecary for all visible messages and other interactions to work properly through day/night and thunder
:cl:
fix: Lumcount now respects area luminosity
/:cl:
> Lumcount now respects area luminosity

- code/modules/mob/living/simple_animal/simple_animal.dm
previously a mob with a disabled AI would still move around, but not do anything else
:cl:
fix: handle automated movement respects AIStatus now
/:cl:
> handle automated movement respects AIStatus now

- code/datums/day_night_controller.dm
The shift will make the cycle more earthlike
:cl:
add: Day/night cycles now have 1.5 hour shift forwards to make the cycles more earth-like
fix: Fixed a bug relating to day/night calculations
/:cl:
> Day/night cycles now have 1.5 hour shift forwards and fixed a bug relating to them

- _maps/RandomRuins/Planet/archeological_site.dmm
I was just enlightened by this idea
:cl:
add: Adds a treasure hunter fedora to the archeological site ruin
/:cl:
> Adds a treasure hunter fedora to the archeological site ruin

- code/datums/day_night_controller.dm
I made a mistake and I meant to shift it backwards, not forwards.
:cl:
fix: Day and night is now correctly shifted backwards. Oops
/:cl:
> Day and night is now correctly shifted backwards

- code/modules/overmap/planets/planetary_mobs.dm
Oversight on my part, I forgot inheritance is a thing
:cl:
fix: Fixes zeqetta's splitting into zeq duchesses
/:cl:
> Fixes zeqetta's splitting into zeq duchesses

- README.md
> Update label-based badges on README

- code/modules/mob/living/carbon/human/species_types/akula.dm
- code/modules/mob/living/carbon/human/species_types/aquatic.dm
- code/modules/mob/living/carbon/human/species_types/ethereal.dm
- code/modules/mob/living/carbon/human/species_types/humanoid.dm
- code/modules/mob/living/carbon/human/species_types/humans.dm
- code/modules/mob/living/carbon/human/species_types/insect.dm
- code/modules/mob/living/carbon/human/species_types/jellypeople.dm
- code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
- code/modules/mob/living/carbon/human/species_types/mammal.dm
- code/modules/mob/living/carbon/human/species_types/mothmen.dm
- code/modules/mob/living/carbon/human/species_types/plasmamen.dm
- code/modules/mob/living/carbon/human/species_types/podpeople.dm
- code/modules/mob/living/carbon/human/species_types/robotic.dm
- code/modules/mob/living/carbon/human/species_types/tajaran.dm
- code/modules/mob/living/carbon/human/species_types/unathi.dm
- code/modules/mob/living/carbon/human/species_types/vox.dm
- code/modules/mob/living/carbon/human/species_types/vulpkanin.dm
- code/modules/mob/living/carbon/human/species_types/xeno.dm
I didn't like seeing `No Description` on every race in character creation, so I made some filler texts until we get lore or cultural stuff set up.
Being able to tell what each species might encompass before choosing it is good.
As a note, I had ZERO idea what to add to Skrell, and Teshari is a testmerge, so that will have to be added in said testmerge.
:cl:
add: Species Descriptions
/:cl:
> (Temporary) Species Descriptions

- code/modules/overmap/planets/planetary_objects.dm
REALLY big oversight on my part
:cl:
fix: Planetary turfs now have planetary atmos
/:cl:
> [red label fix] Planetary turfs now have planetary atmos

- code/game/machinery/computer/_computer.dm
- code/modules/modular_computers/computers/item/computer.dm
- code/modules/modular_computers/computers/item/computer_ui.dm
- code/modules/modular_computers/computers/item/tablet.dm
- code/modules/modular_computers/file_system/program.dm
this time nice
:cl:
add: Keyboard noises for modular consoles and computers
/:cl:
> Keyboard noises for modular consoles and computers

- code/__DEFINES/layers.dm
- code/_onclick/hud/plane_master.dm
- code/game/objects/effects/overlays.dm
Turns out this was unnessecary and without it there's a better blend between the dynamic ones and the normal light
:cl:
add: Dynamic lights now use a different way to render itself, the light transitions should be smoother
/:cl:
> Removes overlay light visual plane

- code/modules/surgery/bodyparts/_bodyparts.dm
:cl:
fix: Fixes invisible non-colorable bodyparts, commonly found on IPC's
/:cl:
> Fixes invisible non-colorable bodyparts

- code/modules/mob/living/carbon/alien/special/alien_embryo.dm
Chest bursting no longer gibs, now instead it'll deal 60 damage to chest and send the victim unconscious for 10 seconds
:cl:
balance: Chest bursting no longer gibs, now instead it'll deal 60 damage to chest and send the victim unconscious for 10 seconds
/:cl:
> Chest bursting no longer gibs

- code/game/objects/items/holy_weapons.dm
- code/game/objects/items/religion.dm
- code/modules/antagonists/cult/cult_items.dm
- code/modules/antagonists/eldritch_cult/eldritch_items.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/head/jobs.dm
- code/modules/clothing/head/misc.dm
- code/modules/clothing/head/misc_special.dm
- code/modules/clothing/masks/animal_masks.dm
- code/modules/clothing/masks/gasmask.dm
- code/modules/clothing/masks/hailer.dm
- code/modules/clothing/masks/miscellaneous.dm
- code/modules/clothing/spacesuits/chronosuit.dm
- code/modules/clothing/spacesuits/miscellaneous.dm
- code/modules/clothing/suits/chaplainsuits.dm
- code/modules/clothing/suits/jobs.dm
- code/modules/clothing/suits/miscellaneous.dm
- code/modules/mob/dead/new_player/sprite_accessories/snout.dm
- code/modules/ninja/suit/head.dm
- code/modules/research/xenobiology/crossbreeding/_clothing.dm
in THIS episode of `horizontal` AZARAK fucking LOOOOSES his mind and goes through EVERY SINGLE HEADWEAR AND MASK and adjusts it?!
:cl:
fix: Fixes mutant variants for head and mask, and HIDESNOUT flag
/:cl:
> Fixes mutant variants for head and mask, and HIDESNOUT flag

- code/datums/weather/weather.dm
:cl:
fix: Weather blend mode and opacity fix
/:cl:
> Weather blend mode and opacity fix

- code/modules/overmap/planets/planetary_mobs.dm
People want them as pets who dont interrupt movement or push things
:cl:
add: Planetary critters now have pass flags
/:cl:
> Planetary critters now have pass flags

- _maps/shuttles/luxury_chilldown.dmm
Fixes and allows the shuttle The Chilldown to spawn.
Fixes unspawnable current content.
> Runtime Errors for The Chilldown Removal

- code/datums/weather/weather_types/sandstorm.dm
I believe they will look better now
:cl:
add: Changes blend mode of sandstorms, they should look better now
/:cl:
> Changes blend mode of sandstorms

- code/modules/excavation/anomalous_crystal.dm
- code/modules/trading/_trade_hub.dm
- code/modules/trading/_trader.dm
- code/modules/trading/bought_goods/goods.dm
- code/modules/trading/sold_goods/goods.dm
- code/modules/trading/traders/goods.dm
The bearcat tradehouse now houses 6 traders from 4
Adds a new trader which trades excavation tools and items, it's a guaranteed spawn for the bearcat tradehouse
:cl:
add: Added an archeology trader, you'll be able to see him always spawn in the FTU tradehouse
/:cl:
> Adds Archeology trader + trading tweaks

- code/modules/mob/dead/observer/observer.dm
Darkness clamped is unmoody, you can still toggle it through the verb
:cl:
qol: Ghosts now start with normal lighting alpha
/:cl:
> Ghosts now start with normal lighting alpha

- code/modules/research/techweb/all_nodes.dm
Ruins the travel vibe and feel of distance from the overmap.
:cl:
del: Removes designs of quantum pads and quantum spin inverters from research nodes
/:cl:
> Removes designs of quantum pads and quantum spin inverters from research nodes

- code/modules/shuttle/shuttle.dm
The freeform ports from freeform docking will now properly get cleaned up and will not leave any ghosts behind that would block docking of other shuttles. They will clean up properly even with shuttle manipulator shanenigans
:cl:
fix: Fixes shuttle freeform port cleanup
/:cl:
> Fixes shuttle freeform port cleanup

- code/modules/mining/machine_vending.dm
Money printing bad, devalues money and other content
:cl:
del: Removes cash redemption from the mining vendor
/:cl:
> Removes cash redemption from the mining vendor

- code/modules/mining/mining_drill.dm
Fixes bugs regarding the terminals
Drills will now disconnect from their nodes if they're on a shuttle that has been moved
Drills will now also, actually drill through the floor, if there is any
:cl:
fix: Fixes mining drill terminal bugs
/:cl:
> Fixes mining drill bugs

- code/modules/overmap/planets/planetary_objects.dm
no more black squares
:cl:
fix: Broken states for planetary turfs
/:cl:
> Broken states for planetary turfs

- code/datums/looping_sounds/machinery_sounds.dm
I like my hearing
Lowers the looping sound of the telecoms machines from 50 to 10. because I like my hearing.
:cl:
qol: Hazzar.. The telecoms machines are no longer deafening.  
/:cl:
> Lower TCOMMS looping vol

- code/game/turfs/open/floor/plating/planet.dm
fixes this
:cl:
fix: Fixes jungle turfs having wrong gas mixes set
/:cl:
> Fixes jungle turfs having wrong gas mixes set

- code/modules/overmap/planets/planetary_objects.dm
:cl:
fix: Fixes outdoors planetary areas having power
/:cl:
> Fixes outdoors planetary areas having power

- code/game/objects/structures/safe.dm
Friend found this bug while making a ruin
:cl:
fix: Moved safe's item insertion to LateInitialize to support spawners
/:cl:
> Moves safe's item insertion to LateInitialize to support spawners

- code/game/objects/structures/rubble.dm
I made it too fragile for normal attacks and such
:cl:
add: Triples rubble integrity
/:cl:
> Triples rubble integrity

- code/modules/power/lighting.dm
:cl:
qol: small lights no longer will be delayed or play a sound
fix: fixed lighting desynchronisation that could be achieved by switching fire alarm and light switch fast
fix: coloring a light no longer will cause the update to be delayed
/:cl:
> Delayed lighting tweaks and fixes

- code/datums/weather/weather_controller.dm
Since no controller overrides this, this is across all weathers
:cl:
balance: Weather now occurs ~33% less frequently
/:cl:
> Weather now occurs ~33% less frequently

- code/game/objects/items/stacks/medical.dm
- code/modules/surgery/bodyparts/bodypart_aid.dm
:cl:
fix: Fixes bandaged limbs being able to be bandaged again, and small examine fix regarding fully ruined bandages
/:cl:
> Fixes bandaged limbs being able to be bandaged again, and small examine fix

- code/modules/mining/mining_drill.dm
:cl:
fix: Fixes mining drills being left behind by shuttles
/:cl:
> Fixes mining drills being left behind by shuttles

- code/modules/overmap/freeform_docker.dm
bug introduced by the planetary turf refactor
:cl:
fix: Fixes shuttles no longer being able to dock on planetary turfs
/:cl:
> Fixes shuttles no longer being able to dock on planetary turfs

- code/modules/mining/equipment/mineral_scanner.dm
I ran into black turfs all around the game and I was wondering why is that
:cl:
fix: Fixes and clarifies the admin debug ore scanner
/:cl:
> Fixes and clarifies the admin debug ore scanner

- code/modules/trading/_trader.dm
I dont think this causes any bugs, but it's bad code I probably did by accident
:cl:
code: Fixes bad code in the trader datum
/:cl:
> Fixes bad code in the trader datum

- code/modules/overmap/planets/planet_types/lush_planet.dm
:cl:
add: Increased flora density on lush planets by ~40%
/:cl:
> Increases flora density on lush planets by ~40%

- code/game/objects/structures/flora.dm
All flora now has 40 integrity (from 150), with the exceptions of trees and rocks
It's hard to clear terrain while all the plants and all have such high integrity
:cl:
balance: All flora now has 40 integrity (from 150), with the exceptions of trees and rocks
/:cl:
> Changes to flora integrity

- _maps/map_files/tradership/tradership1.dmm
- _maps/map_files/tradership/tradership2.dmm
- _maps/map_files/tradership/tradership3.dmm
- _maps/map_files/tradership/tradership4.dmm
Fixed the following:
- Fans under the airlocks
- Disposals pipe in Hydro
- Door access has been removed
- fixed bar dispenser
Added the following
- deck signs to all floors.
- More fun
- peep
:cl:
qol: Bearcat changes, read the pr
/:cl:
> Bearcat QoL Part 4: Doors, Bars, Fans and Signs

- code/game/atoms_movable.dm
Disastrous oversight that causes nulls in lists, and those lists to not clear themselves due to the LAZY behaviour. causing tens thousands of redundant lists
:cl:
fix: Fixed nulls in managed_overlays
/:cl:
> Fixes nulls in managed_overlays

- code/modules/trading/traders/food.dm
Changing some leftover names
:cl:
add: Changes some leftover names of traders
/:cl:
> Pizza Police

- code/modules/overmap/planets/planetary_objects.dm
:cl:
fix: Planetary turfs inherit a proper baseturf now
/:cl:
> Planetary turfs inherit a proper baseturf now

- _maps/RandomRuins/Planet/abandoned_factory.dmm
Must have been an auto-resolve by sdmm
:cl:
fix: Fixes space turfs in abandoned factory ruin
/:cl:
> Fixes space turfs in abandoned factory ruin

- code/modules/excavation/digsite_component.dm
Digsites now properly subtract their lists when something insides them breaks, clarified that it breaks and added a '\' to the 'the'
:cl:
fix: Digsite fix and clarification
/:cl:
> Digsite fix and clarification

- code/modules/power/lighting.dm
Makes planes and layers inherited from parent
:cl:
fix: Fixes light overlays on multi z openspace
/:cl:
> Fixes light overlays on multi z openspace

- code/modules/trading/_bought_goods.dm
- code/modules/trading/_trader.dm
- code/modules/trading/bought_goods/goods.dm
- code/modules/trading/trade_machines.dm
- code/modules/trading/traders/goods.dm
Allows for traders to purchase common items without giving people the means to "print" money
:cl:
add: Traders now can have a limited amount of "stock" they'll purchase. If they run out, it'll rotate (possibly into the same thing)
add: Traders can now purchase reagents
add: Medical trader may now be interested in a reagent of white variety
balance: Medical trader will now purchase a limited amount of organs
/:cl:
> Traders now can have a limited amount of "stock" they'll purchase, and can purchase reagents

- code/modules/mining/ores_coins.dm
fixes https://github.com/hrzntal/horizon/issues/386
Way too light and unwieldy to have any force
:cl:
balance: Coins no longer have any force, and wont hurt anyone when hurled
/:cl:
> Coins no longer have any force

- code/modules/mob/dead/new_player/sprite_accessories/genitals.dm
Somewhat port of https://github.com/Skyrat-SS13/Skyrat-tg/pull/5102 which I helped make long time ago, with code a bit adjusted
Alt click jumpsuit to whip out them george melons
:cl:
fix: Jumpsuits and suits now properly hide/show your privates, based off their coverage.
fix: When you want your privates exposed, not even underwear will block them
/:cl:
> Better hiding/showing of private parts

- code/modules/trading/bought_goods/goods.dm
- code/modules/trading/sold_goods/goods.dm
I wanted to add more goods for traders to potentially buy/sell, but after looking at things, I compulsively started organizing. This is mostly just "cleanup" work so things look like they're where they're supposed to be.
It's not, but it might make things more understandable for the next person who looks at these things.
:cl:
code: Organized the buy/sell goods list used with traders.
/:cl:
> Buy/Sell Trade Datum Sorting

- code/modules/trading/_trader.dm
Kinda high
:cl:
balance: Lowers margin from traders from 30% to 15%, and price variance to 20% from 25%
/:cl:
> Lowers margin from traders from 30% to 15%, and price variance to 20% from 25%

- code/datums/elements/caltrop.dm
- code/game/objects/items/dice.dm
- code/game/objects/items/stacks/sheets/glass.dm
- code/modules/hydroponics/grown/towercap.dm
- code/modules/mining/lavaland/ash_flora.dm
- code/modules/mob/living/simple_animal/hostile/cockroach.dm
- code/modules/power/lighting.dm
The best way to do it for a bespoke element that doesn't know it's source from signals (because it listens to turf, not to the attached object)
:cl:
fix: Fixes caltrops not telling you what you stepped on
/:cl:
> Fixes caltrop component not knowing the real source's name

- code/game/area/areas.dm
Imo it's too loud and the continues shhhhhh is damaging to the ears, especially through the long play sessions we get
:cl:
qol: Lowers ship ambience volume
/:cl:
> Lowers ship ambience volume

- code/controllers/subsystem/overmap.dm
- code/modules/overmap/overmap_objects.dm
- code/modules/overmap/overmap_shuttle.dm
- code/modules/overmap/overmap_visuals.dm
- code/modules/overmap/shuttle_control_component.dm
bug man bad
:cl:
fix: Overmap hard del and logic fixes
/:cl:
> Overmap hard del and logic fixes

- code/datums/chatmessage.dm
Despite the line width being 96, it can be cut as early as uh, maybe 1 or 2 characters less, so around 8 pixels
:cl:
fix: Fixes runechat calculating an improper amount of lines and not displaying the top line
/:cl:
> Fixes runechat calculating an improper amount of lines

- code/__DEFINES/span.dm
> Fixes a missing angled opening bracket for SPAN

- code/modules/mob/mob_say.dm
:cl:
fix: Typing indicator now disappears after sending an emote
/:cl:
> Typing indicator now disappears after sending an emote

- code/modules/research/designs/overmap_machines_designs.dm
OOPS
:cl:
fix: The mining laser design now prints the circuitboard, not the machine
/:cl:
> The mining laser design now prints the circuitboard, not the machine

- code/game/objects/effects/overlays.dm
Probably something to do with the new way its applied, and that it no longer cuts the plane
:cl:
fix: Fixes dynamic lighting overlays
/:cl:
> Fixes dynamic lighting overlays

- code/modules/trading/trade_machines.dm
This allows ghosts to peek into the trader console and see what people are trading/whats their balance etc. (current screen) Better spectating experience. There is a topic check in the actual topic.
:cl:
qol: Removes topic check from trader console UI interact
/:cl:
> Removes topic check from trader console UI interact

- code/modules/mob/dead/observer/observer.dm
:cl:
fix: Fixes ghost hair overlays
/:cl:
> Fixes ghost hair overlays

- code/game/objects/structures/lattice.dm
Looks like they should
:cl:
add: Catwalks can now smooth with fulltile windows
/:cl:
> Catwalks can now smooth with fulltile windows

- code/__HELPERS/customization/mobs.dm
:cl:
fix: Fixes hairstyles in facial hair choice with mismatched parts
/:cl:
> Fixes hairstyles in facial hair choice with mismatched parts

- code/modules/surgery/bodyparts/head.dm
:cl:
fix: Fixes hair overlays on decapitated heads
/:cl:
> Fixes hair overlays on decapitated heads

- code/modules/shuttle/shuttle_purchase_console.dm
:cl:
qol: Adds a disclaimer about dock connection in Shuttle Purchase Console
/:cl:
> Disclaimer about dock connection in Shuttle Purchase Console

- _maps/map_files/KiloStation/KiloStation.dmm
:cl:
fix: Fixes kilo station common dock wrong direction
/:cl:
> Fixes kilo station common dock wrong direction

- code/game/objects/structures/ghost_role_spawners.dm
- code/modules/awaymissions/corpse.dm
- code/modules/ruins/lavaland_ruin_code.dm
You can now use them, there are species and loadout limitations for certain ones
I know the code is not the prettiest, but holy shit, the underlying code is a garbled mess and I dont wanna mess with it more than I have to
:cl:
add: You can now use your pref characters as ghost roles
/:cl:
> Pref characters as ghost roles

- _maps/RandomRuins/SpaceRuins/bigderelict1.dmm
- _maps/RandomRuins/SpaceRuins/oldteleporter.dmm
:cl:
fix: Fixes some improper areas in space ruins
/:cl:
> Fixes some improper areas in space ruins

- code/modules/excavation/excavation_exports.dm
- code/modules/trading/bought_goods/goods.dm
they're too strong
:cl:
balance: Nerfed the price and demand on excavation exports
/:cl:
> Nerfs excavation exports

- code/datums/transit_instance.dm
Gibs and bodyparts bumping against the helm windows and making a sound all the time is a bit annoying, plus it'll be less processing this way, win-win
:cl:
qol: Transit velocity doesn't throw things if they're against something
/:cl:
> Transit velocity doesn't throw things if they're against something

- code/__DEFINES/misc.dm
- code/__DEFINES/mobs.dm
- code/__HELPERS/mobs.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/mob_defines.dm
- code/modules/mob/mob_helpers.dm
Creates and implements a dominant hand system that is set via your character preferences.
Implements and closes https://github.com/hrzntal/horizon/issues/196
:cl:
add: Dominant Handed-ness is now a thing! Change your dominant hand in your character's general information!
/:cl:
> Dominant Handed-ness

- code/modules/mining/mining_drill.dm
>Mine in lavaland
>Drills mines down to lava
>Drill burns to death
:cl:
fix: Drills and braces are now lavaproof
/:cl:
> Drills and braces are now lavaproof

- code/modules/client/loadout/backpack.dm
:cl:
add: Borb plushie is in loadout now
/:cl:
> Borb plushie in loadout

- code/datums/transit_instance.dm
- code/game/turfs/open/space/transit.dm
- code/modules/meteors/meteors.dm
- code/modules/overmap/overmap_hazards.dm
Today on space gear
https://cdn.discordapp.com/attachments/800146077047062558/866331104016597042/2021-07-18_16-44-08.mp4
:cl:
add: Overmap Hazards affect Transit Zones (you can go fishing now in carp schools ,or crash against asteroids) Keep in mind that if you do crash your shuttle on asteroids there is NO WAY for you to be recovered. Another PR will handle that
fix: small fixes and tweaks to transit zones
/:cl:
> Overmap Hazards affect Transit Zones + small fixes

- code/datums/components/overlay_lighting.dm
- code/game/objects/effects/overlays.dm
- code/game/turfs/change_turf.dm
https://github.com/tgstation/tgstation/pull/60218
https://github.com/tgstation/tgstation/pull/60239
I retained the behaviour of directional atom for the purposes of gliding, and adjusted gliding and direction setting to be more natural. Added layer handling because we dont use the extra cutting plane
The cone being an underlay of the holder may create a visual "bug" where the overlay for picking things up(the one that slides onto your character) will have the cone on itself and look weird
:cl:
fix: fixed a bug regarding dynamic luminosity not being retained on ChangeTurf()
refactor: Refactor dynamic lighting to minimise the use of extra atoms and vis contents
/:cl:
> Ports dynamic lighting PR's

- code/game/objects/structures/railings.dm
This will fix all oddities with collisions and railings
:cl:
fix: Added a missing border flag for railings
/:cl:
> Missing border flag for railings

- _maps/RandomRuins/SpaceRuins/forgottenship.dmm
:cl:
fix: Fixes a mapping runtime with forgottenship
/:cl:
> Fixes a mapping runtime with forgottenship

- code/controllers/subsystem/ticker.dm
Ports https://github.com/tgstation/tgstation/pull/60327
related to the job ss refactor
:cl:Rohesie
fix: Fixes a runtime that would leave everyone naked
/:cl:
> Fixes a runtime that would leave everyone naked #60327

- code/datums/components/overlay_lighting.dm
https://github.com/tgstation/tgstation/pull/60336
adjusted for our use of directional atom and also a fix to an oversight of my own
:cl:Rohesie, Azarak
fix: Fixes an underlay movable lighting runtime
fix: Fixed bad logic in updating movable lighting appearance
/:cl:
> Fixes an underlay movable lighting runtime #60336

- code/controllers/subsystem/job.dm
- code/modules/map_content/tradership/tradership_jobs.dm
Fixes getting auto-assigned command roles that dont match the current map
Fixes jobs not showing up if they had another job with a duplicate name (Guess that still doesnt work, i renamed the tradership jobs for now)
:cl:
fix: Fixed reported job issues
/:cl:
> Fixes reported job issues

- code/modules/jobs/job_types/cyborg.dm
- code/modules/jobs/jobs.dm
:cl:
fix: Fixes global list references for silicon positions
/:cl:
> Fixes global list references for silicon positions

- code/game/objects/structures/industrial_lift_structures.dm
:cl:
fix: Borgs can now use the industrial lift controller
/:cl:
> Borgs can now use the industrial lift controller

- code/modules/meteors/meteors.dm
:cl:
fix: Fixes meaty ores halting the MC with connect_loc overhead
/:cl:
> Fixes meaty ores halting the MC with connect_loc overhead

- code/__DEFINES/culture.dm
- code/modules/client/culture/culture/culture_generic.dm
Exotic cultures (other/vatgrown) can now pick a wider variety of languages. There's a disclaimer to only pick those that make sense for your backstory.
More customization should any have a backstory that should give them the language
:cl:
add: Exotic cultures (other/vatgrown) can now pick a wider variety of languages
/:cl:
> Exotic languages for exotic cultures

- code/modules/trading/_bought_goods.dm
- code/modules/trading/_trader_bounty.dm
precursor to mechs and other stuff getting into that pool
:cl:
fix: Cant sell or bounty off things with client mobs inside of them
/:cl:
> Disallow objects with client mobs to be sold or bountied off

- code/modules/client/loadout/backpack.dm
- code/modules/pollution/perfumes.dm
- code/modules/pollution/pollutants/pollutants_generic.dm
:cl:
add: Adds nectarine perfume bottle
/:cl:
> Adds nectarine perfume bottle

- code/modules/trading/_trader_bounty.dm
- code/modules/trading/bounties/trader_bounties.dm
- code/modules/trading/traders/food.dm
- code/modules/trading/traders/goods.dm
we could use even more bounties tbh, more stuff for xenobio extracts, mechs, crafted foods, most notably
:cl:
add: More bounties and gas bounties for traders, eleven of them in total!
/:cl:
> More bounties and gas bounties for traders

- code/modules/trading/_trader.dm
- code/modules/trading/traders/food.dm
They were set a bit too high, when I was playing I found that there were always a ton of bonties or deliveries to do, despite completing plenty
:cl:
balance: Lowers trader bounty and delivery gain chances
/:cl:
> Lowers trader bounty and delivery gain chances

- code/controllers/subsystem/job.dm
- code/modules/jobs/job_types/_job.dm
:cl:
fix: Fixes loadout items not being applied to roundstarted people
/:cl:
> Fixes loadout items not being applied to roundstarted people

- code/game/atoms.dm
Ports https://github.com/tgstation/tgstation/pull/60320 , before I forget about it
Very cheap memory optimization on a large scale
:cl: MrStonedOne
code: optimized memory usage for managed_overlays
/:cl:
> managed_overlays no longer stores as a list for singletons #60320

- code/game/turfs/closed/minerals.dm
- code/game/turfs/closed/wall/mineral_walls.dm
- code/game/turfs/closed/wall/misc_walls.dm
Some walls had improper smoothing and translations after my changes, I only noticed them afterwards and this fixes them
:cl:
fix: Fixes some wall smoothing and translations
/:cl:
> Fixes some wall smoothing and translations

- code/_onclick/click.dm
Ports https://github.com/tgstation/tgstation/pull/62749
It's an annoying input bug
:cl:
fix: Fixes throw mode putting you on click cooldown despite not throwing
/:cl:
> Fixes throw mode putting you on click cooldown despite not throwing #62749

- _maps/map_files/MetaStation/MetaStation.dmm
- code/game/atoms.dm
- code/game/atoms_movable.dm
- code/game/objects/items.dm
- code/modules/vending/_vending.dm
https://github.com/tgstation/tgstation/pull/62243
https://github.com/tgstation/tgstation/pull/62201
https://github.com/tgstation/tgstation/pull/62198
:cl:
code: cleaned up some variables in code
/:cl:
> Variable cleanup PR ports.

- code/modules/atmospherics/machinery/airalarm.dm
:cl:
fix: Fixes icon states and overlays for broken air alarm
/:cl:
> Fixes icon states and overlays for broken air alarm

- code/game/objects/effects/spawners/structure.dm
I must have removed this type by accident during conversion
:cl:
fix: Fixes missing reinforced plasma window spawner
/:cl:
> Fixes missing reinforced plasma window spawner

- code/modules/client/preferences.dm
This will fix the missing common language bug for new players.
:cl:
fix: Properly sets species information when creating a new preference file. This will fix the missing common language bug for new players.
/:cl:
> Properly sets species information when creating a new preference file.

- code/game/objects/structures/low_wall.dm
- code/game/objects/structures/window.dm
- code/modules/mining/equipment/survival_pod.dm
Low walls and windows now smooth with blast doors and shutters much like walls.
:cl:
fix: Fixes consistency in low wall and window smoothing
/:cl:
> Fixes consistency in low wall and window smoothing

- code/modules/mob/living/living.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/living/living_movement.dm
Added a new verb which does what it says on the tin.
More character agency
:cl:
add: You can now stop holding onto things in 0g
/:cl:
> You can now stop holding onto things in 0g

- code/controllers/subsystem/turf_fire.dm
It now properly casts the expected type and checks tick.
:cl:
code: Turf Fire subsystem code improvements
/:cl:
> Turf Fire subsystem code improvements

- code/__DEFINES/atmospherics.dm
- code/game/machinery/doors/firedoor.dm
- code/game/machinery/doors/windowdoor.dm
- code/game/objects/structures/windoor_assembly.dm
- code/game/objects/structures/window.dm
- code/game/turfs/open/openspace.dm
- code/modules/antagonists/blob/structures/_blob.dm
- code/modules/atmospherics/environmental/LINDA_system.dm
- code/modules/shuttle/shuttle_roof.dm
Ports https://github.com/tgstation/tgstation/pull/63270
:cl:
fix:  Fixes up multiz atmos connection, cleans some things up in general
/:cl:
>  Fixes up multiz atmos connection, cleans some things up in general #63270 

- code/game/objects/structures/grille.dm
I have dun fucked when I was fixing an issue and this would use 100% of background processing from the MC
:cl:
fix: Fixes grilles queueing SMOOTHING indefinetly
/:cl:
> Fixes grilles queueing SMOOTHING indefinetly. [important]

- code/modules/mob/living/living.dm
This can prove to be quite tedious with how many of game mechanics floor you.
Game balance often expects people to get up as fast as possible
New players unfamiliar with this will get confused too.
I dont think it's worth to have that for all the balance/tedium and confusion cases it can bring in the current state of the game.
:cl:
balance: Getting floored no longer makes you rest down.
/:cl:
> Getting floored no longer makes you rest down.

- code/game/objects/effects/spawners/structure.dm
typepaths, man
:cl:
fix: Actually fixes reinforced plasma window spawner
/:cl:
> Actually fixes reinforced plasma window spawner

- code/modules/overmap/planets/planet_types/jungle_planet.dm
The jungle mobs are too strong, especially the leapers. Less of them will be more managable but still a challenge
:cl:
balance: Lowers fauna density in jungle planets and leaper spawn chance
/:cl:
> Lowers fauna density in jungle planets and leaper spawn chance

- code/__DEFINES/overmap.dm
- code/controllers/subsystem/mapping.dm
Something that's desired so there's always a planet to chill in
:cl:
add: Guarantees one spawn of a habitable planet
/:cl:
> Guarantees one spawn of a habitable planet

- code/datums/emotes.dm
- code/modules/mob/living/emote.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
- code/modules/mob/mob.dm
- code/modules/mob/mob_say.dm
Now made thinking with OOP programming.
:cl:
add: Subtle and Subtler Anti Ghost emotes, in IC tab
/:cl:
> Subtle and Subtler Anti Ghost

- code/game/objects/items/devices/radio/radio.dm
- code/modules/mapping/space_management/multiz_helpers.dm
Fixes radios in nullspace runtiming.
Fixes get_step_multiz runtiming when trying to step out of world boundaries. (things relying on it already account for receiving a null from this)
:cl:
fix: Some fixes to virtual levels
/:cl:
> Some fixes to virtual levels

- code/controllers/configuration/entries/game_options.dm
- code/controllers/subsystem/gamemode.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/randomverbs.dm
- config/game_options.txt
Previously did nothing. Now is relevant.
:cl:
code: ALLOW_RANDOM_EVENTS is now HALT_STORYTELLER config
/:cl:
> ALLOW_RANDOM_EVENTS is now HALT_STORYTELLER config

- code/game/blind_effect.dm
As in, being nearsighted and having your vision corrected. I forgot a return value.
:cl:
fix: Fixes blind effects playing for nearsighted people with their vision corrected
/:cl:
> Fixes blind effects playing for vision corrected people

- code/_onclick/hud/parallax.dm
Ports https://github.com/yogstation13/Yogstation/pull/12252
and https://github.com/tgstation/tgstation/pull/59759
Actually makes parallax works once again, and more efficiently too.
:cl:
fix: Fixed parallax animation.
/:cl:
> Parallax fix and removed not needed animate

- code/modules/ambience/ambience_controller.dm
This is dumb and shouldn't happen, but it does. oh well.
:cl:
fix: Fixes ambience controller runtime error
/:cl:
> Fixes ambience controller runtime error

- code/datums/components/storage/concrete/wallet.dm
Fixes this
:cl:
fix: Fixes alternate wallet action click chain
/:cl:
> Fixes alternate wallet action click chain

- code/controllers/subsystem/mapping.dm
- code/modules/holodeck/computer.dm
- code/modules/mapping/mapping_helpers.dm
- code/modules/mapping/space_management/zlevel_manager.dm
- code/modules/unit_tests/unit_test.dm
hopefully
A whole level has been dedicated to unit tests because they actually use space outside of the box for generation testing.
New zlevels created after SSatoms initialized will initialize its turfs now.
Added a warning return to a mapping helper of Ians New Year celebration.
Holodeck computer will no longer try to initialize stuff without a holodeck area in the world
:cl:
fix: Fixes bugs failing CI
/:cl:
> Fixes bugs failing CI

- code/game/turfs/closed/wall/mineral_walls.dm
I now actually sampled the previous palette instead of inputting a hex from guesswork and being like "yeah it'll be fine"
:cl:
add: Better paint colors for survival pod walls
/:cl:
> Better paint colors for survival pod walls

- code/game/shuttle_engines.dm
- code/modules/overmap/propulsion_engine.dm
Adds examines for shuttle engines construction states
:cl:
add: Adds examines for shuttle engines construction states
/:cl:
> Examines for shuttle engines construction states

- code/__DEFINES/achievements.dm
- code/__HELPERS/roundend.dm
- code/controllers/subsystem/processing/quirks.dm
- code/controllers/subsystem/ticker.dm
- code/datums/achievements/misc_scores.dm
- code/datums/quirks/_quirk.dm
- code/datums/quirks/negative.dm
- code/modules/client/preferences.dm
- code/modules/mob/dead/new_player/preferences_setup.dm
Random hardcore is a mode that gives you a randomly generated (lol) character with a couple of bad quirks and gives you some """points""" for surviving to the end of the round. This has no place for any existance in a roleplay server.
:cl:
del: Completely removes random hardcore
/:cl:
> Completely removes random hardcore

- code/modules/events/mold.dm
- code/modules/mold/mold_structures.dm
- tgstation.dme
Mold is now a major event that can spawn.
Mold core now has more integrity (800)
Mold core attacks now have chat feedback and respect armor values.
:cl:
add: Added an event which spawns Mold and made some tweaks to it.
/:cl:
> Makes Mold an event & Mold tweaks

- code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
They'd try to make overlays despite no reagents
:cl:
fix: Fixes reagent overlays for glasses
/:cl:
> Fixes reagent overlays for glasses

- code/modules/ambience/ambience_controller.dm
i messed up
:cl:
fix: Fixes ship ambience volume handling
/:cl:
> Fixes ship ambience volume handling

- code/__DEFINES/construction.dm
- code/game/objects/items/stacks/sheets/glass.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/game/objects/items/stacks/sheets/sheets.dm
- code/game/objects/structures/grille.dm
- code/game/objects/structures/low_wall.dm
Something I probably should have done before.
You can now install windows or deconstruct low walls through an RCD
You can now install windows on low walls by the use of sheets.
Installing windows on things is now a generic behaviour of a sheet.
:cl:
add: You can now deconstruct low walls by use of RCD
fix: You can now install windows on low walls by use of sheets of RCD
/:cl:
> Low wall window mounting and RCD actions

- _maps/map_files/tradership/tradership3.dmm
Probably fixes https://github.com/hrzntal/horizon/issues/645
:cl:
fix: Fixes gravity generator issues on bearcat
/:cl:
> Fixes gravity generator issues on bearcat

- code/game/objects/items/paint.dm
- code/modules/vending/youtool.dm
2 in stock, 200 credits each
Good to give people a tool to renovate even harder.
:cl:
add: Adaptive paint can be purchased from YouTool
/:cl:
> Adaptive paint can be purchased from YouTool

- code/controllers/subsystem/air.dm
- code/datums/map_zones.dm
- code/modules/atmospherics/environmental/LINDA_turf_tile.dm
fixes https://github.com/hrzntal/horizon/issues/660
:cl:
fix: Fixes planetary atmos on changed turfs (gas from mined rocks)
/:cl:
> Fixes planetary atmos on changed turfs

- code/datums/chatmessage.dm
Should make it better readable, but not yet quite white-ish
:cl:
add: Makes runechat emote color a notch higher
/:cl:
> Makes runechat emote color a notch higher

- code/game/machinery/computer/camera_advanced.dm
- code/game/machinery/hologram.dm
Due to being invoked by user input (or possibly creating some recursive loop I yet am not seeing) this is a crash vector that is being fixed.
and yeah bugs be gone
:cl:
fix: Fixes issues with holopads and remote eyes
/:cl:
> Fixes issues with holopads and remote eyes

- code/game/objects/items/stacks/catwalk.dm
Adds an examine tidbit about the usage of the stacks
closes https://github.com/hrzntal/horizon/issues/735
:cl:
add: Clarifies catwalk stack usage
/:cl:
> Clarifies catwalk stack usage

- code/__DEFINES/mobs.dm
- code/modules/clothing/under/_under.dm
- code/modules/mob/living/carbon/carbon_update_icons.dm
- code/modules/mob/living/carbon/human/human_update_icons.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/human/species_types/teshari.dm
fixes https://github.com/hrzntal/horizon/issues/702
:cl:
fix: Fixes accessories not getting offsets
/:cl:
> Fixes accessories not getting offsets, improves clothing render code

- code/game/machinery/doors/door.dm
- code/game/machinery/doors/poddoor.dm
fixes https://github.com/hrzntal/horizon/issues/748
:cl:
code: Better door auto align
/:cl:
> Better door auto align

- code/modules/admin/verbs/adminhelp.dm
- code/modules/admin/verbs/adminpm.dm
My god this is a spaghetti
closes https://github.com/hrzntal/horizon/issues/738 ?
:cl:
fix: Sanitize ahelp communication
/:cl:
> Sanitize ahelp communication

- code/game/machinery/spaceheater.dm
fixes https://github.com/hrzntal/horizon/issues/683
:cl:
fix: Fixes space heater attack chain
/:cl:
> Fixes space heater attack chain

- code/modules/admin/verbs/atmosdebug.dm
Closes https://github.com/hrzntal/horizon/issues/722
:cl:
fix: Fixes check power cable debug layers
/:cl:
> Fixes check power cable debug layers

- code/game/atoms_movable.dm
- code/game/objects/items.dm
- code/modules/mob/inventory.dm
ports  [Item Pickup Brush-Up #64095 ](https://github.com/tgstation/tgstation/pull/64095)
Which fixes attack animations and adds pickup and drop animations
Better feedback
:cl: LemonInTheDark
add: Adds pickup and drop animations
fix: Fixed attack item overlay
/:cl:
> Item Pickup Brush-Up #64095

- code/_onclick/hud/plane_master.dm
- code/modules/client/preferences.dm
Fixes https://github.com/hrzntal/horizon/issues/503
:cl:
fix: Fixes ambient occlusion preference
/:cl:
> Fixes ambient occlusion preference

- code/modules/vehicles/mecha/working/ripley.dm
Fixes https://github.com/hrzntal/horizon/issues/426
Refactors the code to remove duplicate code and fix a bug with loose box reference
:cl:
qol: Added feedback when a cargo falls out of ripley compartment due to explosion
refactor: Refactors ripley cargo code
/:cl:
> Refactors ripley cargo code and adds feedback

- code/game/turfs/closed/wall/misc_walls.dm
Fixes https://github.com/hrzntal/horizon/issues/656
Handled by the type because we dont have a concrete material as of now. (And i dont wanna add new materials until we get to reworking their system)
:cl:
fix: Removed RCD interactions from concrete walls
/:cl:
> Removes RCD interactions from concrete walls

- code/modules/client/client_procs.dm
Ports https://github.com/tgstation/tgstation/pull/64536
But makes the comment slightly more informative
:cl: LemonInTheDark
fix: Fixed client deletion signalling
/:cl:
> Ensures that COMSIG_PARENT_QDELETING is sent before client Destroy.

- code/game/machinery/cryopod.dm
Fixes https://github.com/hrzntal/horizon/issues/774
Adds a do_after to the cryopod taking 3 seconds to enter or put someone in it
Removed duplicate code
Added more feedback
Added admin message when someone resists out of cryo
:cl:
qol: More feedback regarding cryo pods
qol: Now it takes 3 seconds to climb into a cryo pod
fix: Fixed a bug that prevented people from being cryod
/:cl:
> Cryopod fixes and improvements

- code/datums/atmosphere/_atmosphere.dm
It was previously very badly made. Now it uses math to calculate everything
:cl:
fix: Fixes planet atmosphere gas string generation, which will guarantee that Lavaland always has low pressure atmos
/:cl:
> Fixes planet atmosphere gas string generation

- code/modules/shuttle/sold_shuttles.dm
Increased from 1. With long shifts and very limited amount of actual shuttles, it's easy to buy them all out (not including the build your own ones)
:cl:
add: All purchasable shuttles have now stock 2
/:cl:
> All purchasable shuttles now have a stock of 2

- code/__DEFINES/overmap.dm
Closes https://github.com/hrzntal/horizon/issues/791
it is habitable after all
:cl:
add: Adds desert planet to habitable planets spawn pool
/:cl:
> Adds desert planet to habitable planets spawn pool

- code/datums/materials/alloys.dm
It now will be slightly brighter gray with a red hue, instead of a purple hue
:cl:
qol: Plastitanium walls now have a better color
/:cl:
> Sets a better plastitanium wall color

- _maps/map_files/Deltastation/DeltaStation2.dmm
- _maps/map_files/IceBoxStation/IceBoxStation.dmm
- _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
- _maps/map_files/KiloStation/KiloStation.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/PubbyStation/PubbyStation.dmm
- _maps/map_files/tramstation/tramstation.dmm
- _maps/shuttles/emergency_monastery.dmm
- code/_globalvars/lists/mapping.dm
- code/game/objects/effects/landmarks.dm
So Let me take you on a journey. to 6 years ago in TG land.
They had created this neat event spawner landmark to be used with there new portal storm event.
It was great. All the mappers placed them all over the map. Great times were had.
The spawner even got used for some other events.
Then Disaster struck for our poor landmark...
4 Years ago, A coder implemented a new system of spawning... The find_station_turf proc.
It made spawning mobs for events so much better...
But something was forgotten.. left to collect dust.. Our lowly Generic Event Spawner landmark.
And of course.. all the mappers were told it was not in use anymore....
Oh... What? You are telling me.. No one told the mappers that that landmark has no use anymore!?! Madness...
So the wonderful mappers kept placing this marker …
> Remove the unsed landmark and cleans up maps

- code/__DEFINES/layers.dm
- code/game/machinery/navbeacon.dm
Fixes https://github.com/hrzntal/horizon/issues/828
:cl:
fix: Navigation beacons now display under catwalks
/:cl:
> Navigation beacons now display under catwalks

- code/modules/power/cable.dm
Fixes https://github.com/hrzntal/horizon/issues/843
:cl:
fix: Fixes a cut type of cable coil being invisible
/:cl:
> Fixes a cut type of cable coil being invisible

- code/game/objects/structures/fireplace.dm
- code/modules/hydroponics/grown/towercap.dm
Fixes https://github.com/hrzntal/horizon/issues/822
Triples the time things burn in the fireplace
:cl:
add: Triples the time things burn in the fireplace
fix: You can now add logs to the fireplace
/:cl:
> You can now add logs to the fireplace, fireplace improvements

- code/__HELPERS/piping_colors_lists.dm
- code/modules/atmospherics/machinery/atmosmachinery.dm
Fixes https://github.com/hrzntal/horizon/issues/737
The added layer from colors actually doesnt make any layering work properly, dont believe the comment, this function is useless and only causes inconsistencies
:cl:
fix: Fixes inconsistent pipe layering
/:cl:
> Fixes inconsistent pipe layering

- code/modules/client/preferences.dm
Title
Less confused people as to why they cant join as job X or Y because there's not enough space to be descriptive in the occupation selector.
:cl:
add: Adds a warning about job language requirements
/:cl:
> Adds a warning about job language requirements

- code/modules/client/preferences.dm
- code/modules/client/preferences_loadout.dm
We dont have a system for creating complex initial values for prefs, and I had thought save/load would go through this anyway, but it doesn't so this is sort of a bandaid until such a system gets implemented
:cl:
fix: Fixes loadouts being broken for completely new prefs
/:cl:
> Fixes loadouts being broken for completely new prefs

- code/game/objects/structures/industrial_lift.dm
- code/modules/mob/living/living.dm
It has now proper conditions and the tram has now a proper flag.
:cl:
fix: Fixes looking down a z level
/:cl:
> Fixes looking down a z level

- code/__DEFINES/is_helpers.dm
- code/datums/mind.dm
- code/modules/mob/living/silicon/ai/ai.dm
The only two cases I could find
:cl:
fix: Fixes cases of string use of assigned_role
/:cl:
> Fixes cases of string use of assigned_role

- code/modules/trading/bought_goods/goods.dm
:cl:
add: Some trading tweaks
/:cl:
> Some trading tweaks

- code/game/atoms.dm
One of my PR's fixing the gravity generator feedback fixed other stuff and probably uncovered this bug
If previously this code worked fine then it means that gravity generators didn't update their `on` variable.
Fixes https://github.com/hrzntal/horizon/issues/932
:cl:
fix: fFixes gravity from disabled gravity generators
/:cl:
> Fixes gravity from disabled gravity generators

- code/controllers/subsystem/mapping.dm
The reason why the end is "sticky" becaues that's the end of the physical map, and you can't throw something in reverse of your direction because there are no turfs to target. Adding a reserved edge from a virtual level fixes this.
Also some small improvements to code
Fixes https://github.com/hrzntal/horizon/issues/925
:cl:
fix: Ruin levels now have a reserved margin, you no longer will get "stickied" to its edges
/:cl:
> Ruin levels now have a reserved margin

- code/modules/mob/mob_say.dm
😳 
:cl:
qol: Large input box for subtler anti ghost
/:cl:
> Large input box for subtler anti ghost

- code/game/objects/structures/shower.dm
- code/game/objects/structures/watercloset.dm
I did an óópsie
:cl:
fix: Fixes directionals for showers and sinks
/:cl:
> Fixes directionals for showers and sinks

- code/__DEFINES/layers.dm
- code/modules/power/terminal.dm
Also fixed up a scrubber layer order, that doesn't really matter as it's on a different plane anyway but it's nice to have the game plane layers not mixed up with floor plane layers
:cl:
imageadd: Terminals are now visually under catwalks
/:cl:
> Terminals are now under catwalks

- code/modules/mob/dead/new_player/sprite_accessories/ears.dm
- code/modules/mob/dead/new_player/sprite_accessories/frills.dm
- code/modules/mob/dead/new_player/sprite_accessories/horns.dm
They previously would just not.
:cl:
fix: Frills, ears, horns show up on robotic heads
/:cl:
> Frills, ears, horns show up on robotic heads

- code/datums/industrial_lift/lift_controller.dm
- code/datums/looping_sounds/machinery_sounds.dm
- code/game/objects/structures/industrial_lift_structures.dm
Lowers the volume of their rumbling loop aswell as the elevator dings. They were a tad bit too high I think.
:cl:
add: Industrial lifts are a bit more quiet now
/:cl:
> Quieter industrial lifts

- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/human/species_types/vox.dm
This got broken when I introduced Teshari and all the code improvements for bodytypes with them.
:cl:
fix: Fixes Vox not getting proper headwear sprite variants
/:cl:
> Fixes Vox not getting proper headwear sprite variants

- code/datums/shuttles.dm
- code/modules/admin/verbs/map_template_loadverb.dm
- code/modules/mapping/map_template.dm
Title, I did an oopise and forgot to pass the argument further.
:cl:
fix: Fixes ruins not clearing turfs and adds that option to the template spawn verb
/:cl:
> Fixes ruins not clearing turfs and adds that option to the template spawn verb

- code/modules/reagents/chemistry/recipes/others.dm
Fixes #1054 
Ice is now silent when melting.
Bugs & oversights bad
:cl:
fix: Ice no longer makes a noise when melting.
/:cl:
> Fix ice reaction noise

- code/datums/materials/meat.dm
- code/datums/materials/pizza.dm
- code/game/objects/items/food/burgers.dm
- code/game/objects/items/food/meat.dm
- code/game/objects/items/food/pastries.dm
- code/modules/hydroponics/grown/flowers.dm
- code/modules/hydroponics/grown/kudzu.dm
Some very smart person made the materials which food is made out of apply an edible component, overwriting the edible component of the food, making it so none of the foodtypes flags and more, made sense. This PR removes those behaviours.
Removes a lot of GROSS flags because I guess that person has also happens to be allergic to meat and put GROSS on every article of it.
:cl:
fix: Fixes foodtypes and removes some GROSS flags. Yes this will fix cooked meat seem not cooked.
/:cl:
> Fixes foodtypes and removes some GROSS flags

- code/modules/clothing/under/syndicate.dm
Adds sensors to the Tacticool Turtle and skirtle neck
Sensors on loadout items good.
:cl:
qol: Add Sensors to the Tacticool Turtleneck and Skirtleneck
/:cl:
> Adds Sensors to tacticool turtleneck/skirtleneck

- code/modules/slapcraft/base_steps/slapcraft_step_reagent.dm
- code/modules/slapcraft/base_steps/slapcraft_step_reagent_container.dm
Checks if reagents datum exists, it should in most cases but who knows
> More sanity for reagent steps in Slapcrafting

- .github/workflows/update_tgs_dmapi.yml
- Updated checkout action to v3
- Updated commit ident to GitHub Actions
> Update TGS DMAPI workflow: checkout v3; commit id
